### ISSUE TITLE
Can't copy selected text / Quote

### ISSUE THREAD

**Issue by PolynomialDivision** [iNPUTmice/Conversations#2518]
#### General information

* **Version:** 1.18.5
* **Device:** Xiaomi Redmi Note 3 Pro Global
* **Android Version:** MIUI 8.2.4.0 Stable (Android 6.0.1 MMB29M)
* **Server name:** self hosted
* **Server software:** prosody 0.10
* **Installed server modules:** all
* **Conversations source:** PlayStore

#### Steps to reproduce

1. Open A Chat Window
2. Select text
3. Try to copy text
4. Try to quote text

#### Expected result

I'm only allowed to mark the whole text in a conversations "bubble". I would assume that over the selected text a window pops out with options (copy|share|...) but this isn't happening. Furthermore I can't change the selection (so pushing around the end and the beginning of the marker).

When I select a message I can't quote it.

#### Debug output

(adb logcat  doesn't show anything important)

**Comment by iNPUTmice** [comment]
Looks like this is specific to your ROM. I'm afraid I can't help you with that since I don't own a Xiaomi device. If you want to work on that yourself I can give you some hints on where to start digging into this if you step by our MUC.

**Comment by PolynomialDivision** [comment]
Yeah I would like to get some hints.
May I have time to look in the code. :)

**Comment by iNPUTmice** [comment]
Have a look at the classes `CopyTextView`, ` ClickableMovementMethod` and `ListSelectionManager` all of which are in the ui.widget package. Selection via context menu starts here: https://github.com/siacs/Conversations/blob/1.18.5/src/main/java/eu/siacs/conversations/ui/ConversationFragment.java#L741

**Comment by PolynomialDivision** [comment]
If somebody follows this issue

You have to disable Miui Optimizations to use android studio... ^^

https://stackoverflow.com/questions/42626035/unable-to-install-android-app-via-usb-debugging

**Comment by PolynomialDivision** [comment]
Ok I just printed the error message xD

https://github.com/siacs/Conversations/blob/1.18.5/src/main/java/eu/siacs/conversations/ui/widget/ListSelectionManager.java#L211

And I get this:

    java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Method.invoke(Native Method)
    at eu.siacs.conversations.ui.widget.ListSelectionManager.startSelection(    ListSelectionManager.java:215)
    at eu.siacs.conversations.ui.widget.ListSelectionManager.startSelection(    ListSelectionManager.java:201)
    at eu.siacs.conversations.ui.ConversationFragment.selectText(ConversationFragment.java:754)
    at eu.siacs.conversations.ui.ConversationFragment.onContextItemSelected(    ConversationFragment.java:670)
    at android.app.Fragment.performContextItemSelected(Fragment.java:2341)
    at android.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2088)
    at android.app.FragmentController.dispatchContextItemSelected(FragmentController.java:303)
    at android.app.Activity.onMenuItemSelected(Activity.java:2986)
    at com.android.internal.policy.PhoneWindow$DialogMenuCallback.onMenuItemSelected(    PhoneWindow.java:5012)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
    at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
    at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108)
    at android.widget.AdapterView.performItemClick(AdapterView.java:310)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3081)
    at android.widget.AbsListView$3.run(AbsListView.java:3947)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5441)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
    Caused by: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 0
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.add(ArrayList.java:147)
    at com.android.internal.view.menu.ActionMenu.add(ActionMenu.java:66)
    at com.android.internal.view.menu.ActionMenu.add(ActionMenu.java:60)
    at eu.siacs.conversations.ui.adapter.MessageAdapter$MessageBodyActionModeCallback.onCreateActionMode(    MessageAdapter.java:870)
    at eu.siacs.conversations.ui.widget.ListSelectionManager$CustomCallback.onCreateActionMode(    ListSelectionManager.java:132)
    at android.widget.Editor.startSelectionActionModeInternal(Editor.java:1760)
    at android.widget.Editor.startSelectionActionMode(Editor.java:1713)
    at java.lang.reflect.Method.invoke(Native Method) 
    at eu.siacs.conversations.ui.widget.ListSelectionManager.startSelection(ListSelectionManager.java:215    ) 
    at eu.siacs.conversations.ui.widget.ListSelectionManager.startSelection(ListSelectionManager.java:201    ) 
    at eu.siacs.conversations.ui.ConversationFragment.selectText(ConversationFragment.java:754) 
    at eu.siacs.conversations.ui.ConversationFragment.onContextItemSelected(ConversationFragment.java:670    ) 
    at android.app.Fragment.performContextItemSelected(Fragment.java:2341) 
    at android.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2088) 
    at android.app.FragmentController.dispatchContextItemSelected(FragmentController.java:303) 
    at android.app.Activity.onMenuItemSelected(Activity.java:2986) 
    at com.android.internal.policy.PhoneWindow$DialogMenuCallback.onMenuItemSelected(    PhoneWindow.java:5012) 
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761) 
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152) 
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904) 
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894) 
    at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167) 
    at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108) 
    at android.widget.AdapterView.performItemClick(AdapterView.java:310) 
    at android.widget.AbsListView.performItemClick(AbsListView.java:1145) 
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3081) 
    at android.widget.AbsListView$3.run(AbsListView.java:3947) 
    at android.os.Handler.handleCallback(Handler.java:739) 
    at android.os.Handler.dispatchMessage(Handler.java:95) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5441) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by PolynomialDivision** [comment]
Cause (sorry never developed android application):
    java.lang.IndexOutOfBoundsException: Invalid index 3, size is 0
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.add(ArrayList.java:147)
    at com.android.internal.view.menu.ActionMenu.add(ActionMenu.java:66)
    at com.android.internal.view.menu.ActionMenu.add(ActionMenu.java:60)
    at eu.siacs.conversations.ui.adapter.MessageAdapter$MessageBodyActionModeCallback.onCreateActionMode(    MessageAdapter.java:870)
    at eu.siacs.conversations.ui.widget.ListSelectionManager$CustomCallback.onCreateActionMode(    ListSelectionManager.java:132)
    at android.widget.Editor.startSelectionActionModeInternal(Editor.java:1760)
    at android.widget.Editor.startSelectionActionMode(Editor.java:1713)
    at java.lang.reflect.Method.invoke(Native Method)
    at eu.siacs.conversations.ui.widget.ListSelectionManager.startSelection(    ListSelectionManager.java:215)
    at eu.siacs.conversations.ui.widget.ListSelectionManager.startSelection(    ListSelectionManager.java:201)
    at eu.siacs.conversations.ui.ConversationFragment.selectText(ConversationFragment.java:754)
    at eu.siacs.conversations.ui.ConversationFragment.onContextItemSelected(    ConversationFragment.java:670)
    at android.app.Fragment.performContextItemSelected(Fragment.java:2341)
    at android.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2088)
    at android.app.FragmentController.dispatchContextItemSelected(FragmentController.java:303)
    at android.app.Activity.onMenuItemSelected(Activity.java:2986)
    at com.android.internal.policy.PhoneWindow$DialogMenuCallback.onMenuItemSelected(    PhoneWindow.java:5012)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
    at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167)
    at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108)
    at android.widget.AdapterView.performItemClick(AdapterView.java:310)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3081)
    at android.widget.AbsListView.onTouchUp(AbsListView.java:3959)
    at android.widget.AbsListView.onTouchEvent(AbsListView.java:3696)
    at android.view.View.dispatchTouchEvent(View.java:9306)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2548)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2241)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2255)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
    at android.app.Dialog.dispatchTouchEvent(Dialog.java:790)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
    at android.view.View.dispatchPointerEvent(View.java:9526)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4267)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4133)
    at android.view.ViewRootImpl$InputStage.d
    06-28 12:27:22.571 17424-17424/eu.siacs.conversations W/InputEventReceiver: Attempted to finish an     input event but the input event receiver has already been disposed.

**Comment by licaon-kter** [comment]
Please paste these at https://gist.github.com and post the link here, instead of these walls of text.

**Comment by PolynomialDivision** [comment]
Ok.
But I have no idea how to continue. :/

**Comment by WarrenBKN** [comment]
work around, praise the Lord

long click
share with...
copy to clipboard

app Clip Stack.  Though development halted I prefer it to the 3 dozen non-malware apps i tested.

 (adware is malware)

https://github.com/heruoxin/Clip-Stack

Jabber Texting FTW!

**Comment by PolynomialDivision** [comment]
Sorry but I don't want a work around for hits. (sensible information etc ...)

I postet this bug at the [xiaomi forum](http://en.miui.com/thread-691635-1-1.html)... But I don't think they will help us.

@iNPUTmice : Can u tell me if there are other [selection types](
https://github.com/siacs/Conversations/blob/1.18.5/src/main/java/eu/siacs/conversations/ui/widget/ListSelectionManager.java#L178) I can try?

    String[] startSelectionNames = {"startSelectionActionMode", "startSelectionActionModeWithSelection"};

**Comment by PolynomialDivision** [comment]
I think we can close.
It is not possible to select sepcific text when you quote or copy. Just whole message will be quoted or copied. Everything works nice on Xiaomi Redmi Note 3 with latest stable. :)
