### ISSUE TITLE
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)

### ISSUE THREAD

**Issue by wainaina** [iNPUTmice/Conversations#2824]
#### General information

* **Version:** eg 1.21.0
* **Device:** eg Google Nexus 5
* **Android Version:** eg Android 6.0 Stock
* **Server name:** eg self hosted
* **Server software:** openfire
* **Installed server modules:** eg Stream Managment, CSI, MAM
* **Conversations source:** eg self build

#### Steps to reproduce

1. … Create a Contact
2. … Start a new conversation with the created contact.
#### Expected result
Insertion of a conversation record in conversations table

What is the expected output? 
N/A

#### Actual result
Unfortunaltely, Conversations has stopped.

What do you see instead?
The application throws an error.

#### Debug output

Error inserting read=1 uuid=6d62bedd-b2cd-4e1c-af1d-1738247433d9 body=Hi Business By Sam
                                                                 
                                                                 This is Samuel Wainaina. I'm interested in your products. How do i get a hold of you? conversationUuid=1f8327ad-8b4c-4ec0-b6b8-3fe562c58c66 serverMsgId=null axolotl_fingerprint=null edited=null trueCounterpart=null status=5 carbon=0 relativeFilePath=null encryption=0 timeSent=1519298323724 counterpart=b_40@red5 type=0 oob=0 remoteMsgId=null
                                                                 android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
                                                                     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1474)
                                                                     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
                                                                     at eu.siacs.conversations.persistance.DatabaseBackend.createMessage(DatabaseBackend.java:399)
                                                                     at eu.siacs.conversations.services.XmppConnectionService.sendMessage(XmppConnectionService.java:1017)
                                                                     at eu.siacs.conversations.services.XmppConnectionService.sendMessage(XmppConnectionService.java:874)
                                                                     at eu.siacs.conversations.ui.ConversationFragment.sendPlainTextMessage(ConversationFragment.java:1197)
                                                                     at eu.siacs.conversations.ui.ConversationFragment.sendMessage(ConversationFragment.java:377)
                                                                     at eu.siacs.conversations.ui.ConversationFragment.access$700(ConversationFragment.java:72)
                                                                     at eu.siacs.conversations.ui.ConversationFragment$8.onClick(ConversationFragment.java:318)
                                                                     at android.view.View.performClick(View.java:5610)
                                                                     at android.view.View$PerformClick.run(View.java:22265)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
adb logcat -s conversations
````

**Comment by Donyme** [comment]
Go to Settings->Applications->Conversation.im->storage->clear cache. 
After this run the app again , probably this will prevent the app from crashing.
