### ISSUE TITLE
Hide Microphone button in video-only session

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/Conversations#3700]
Another client could potentially offer us a video-only session (which we would accept);

The UI would still try to display a MIC enable/disable button and try to discover the current microphone state which will fail with an IllegalStateException because no Audio Track has been set up.

```
java.lang.IllegalStateException: Local audio track does not exist (yet)                                                                                                                              
    at eu.siacs.conversations.xmpp.jingle.WebRTCWrapper.isMicrophoneEnabled(WebRTCWrapper.java:309)                                                                                              
    at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.isMicrophoneEnabled(JingleRtpConnection.java:1033)                                                                                 
    at eu.siacs.conversations.ui.RtpSessionActivity.updateInCallButtonConfiguration(RtpSessionActivity.java:583)                                                                                 
    at eu.siacs.conversations.ui.RtpSessionActivity.updateButtonConfiguration(RtpSessionActivity.java:553)                                                                                       
    at eu.siacs.conversations.ui.RtpSessionActivity.lambda$onJingleRtpConnectionUpdate$4$RtpSessionActivity(RtpSessionActivity.java:849)                                                         
    at eu.siacs.conversations.ui.-$$Lambda$RtpSessionActivity$zwP4CbuJkR2JW_EyCmT42WhqMYw.run(Unknown Source:8)                                                                                  
    at android.os.Handler.handleCallback(Handler.java:873)                                                                                                                                       
    at android.os.Handler.dispatchMessage(Handler.java:99)                                                                                                                                       
    at android.os.Looper.loop(Looper.java:214)                                                                                                                                                   
    at android.app.ActivityThread.main(ActivityThread.java:7073)                                                                                                                                 
    at java.lang.reflect.Method.invoke(Native Method)                                                                                                                                            
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)                                                                                                         
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965
```

**Comment by wiktor-k** [comment]
D'oh :facepalm: I forgot to attach the demo page I used to trigger this:

https://metacode.biz/sandbox/jingle-demo

If you have a spare account you can log in ([it should autodiscover websocket URL](https://compliance.conversations.im/server/conversations.im/)).

Select "Use screen" (this triggers selecting screen sharing instead of mic/camera). and then Connect.

Enter your own JID in Peer JID (for me it didn't work with bare JIDs, full JID was necessary) and Call. Answering the call in Conversations crashed the app.

(for the record there is no backend there, the app directly connects to the target server).

I will re-test this when a new beta hits GP but this may be useful for some debugging anyway.

**Comment by wiktor-k** [comment]
Yep, this works now. Thanks for your work! :+1:
