### ISSUE TITLE
App keeps crashing on start on device with of order audio system.

### ISSUE THREAD

**Issue by tuxayo** [iNPUTmice/Conversations#3712]
#### General information

* **Version:** 2.8.2
* **Device:** Galaxy S5
* **Android Version:**  Android 9 (LineageOS for microG 16)
* **Server name:** conversations.im
* **Conversations source:** F-Droid

#### Steps to reproduce
Nothing. Actually some time after the upgrade I got the 1st Android message about the crash. (background service?)
Then I tried to open the app and it just crashes.

Very important info: my device has suffered massive damage from previous owner and nothing related to audio works. 
- ear piece
- speaker
- jack
- microphone

Thus many apps crash when trying to use audio.

I'm pretty sure it's related to that due to the logs and the fact that the upgrade was from 2.7.X to 2.8.X

```
at android.media.ToneGenerator.<init>(ToneGenerator.java:746)
at eu.siacs.conversations.xmpp.jingle.ToneManager.<init>(ToneManager.java:24)
```

#### Debug output
BTW, `adb logcat -s conversations` is too restrictive:
````
05-10 14:43:28.274 11748 11748 D conversations: action: null
05-10 14:43:28.323 11748 11748 D conversations: ConversationsOverviewFragment.onStart()
05-10 14:43:28.324 11748 11748 D conversations: ConversationsOverviewFragment.onResume()
````

full logs
````
05-10 14:41:28.546   576   620 I chatty  : uid=1000(system) ActivityManager identical 3 lines
05-10 14:41:29.549   576   620 W ActivityManager: Scheduling restart of crashed service eu.siacs.conversations/.services.XmppConnectionService in 1000ms
05-10 14:41:29.616   576 26141 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=eu.siacs.conversations/.ui.ConversationActivity bnds=[731,1217][935,1455]} from uid 10095
05-10 14:41:29.665   576   622 I ActivityManager: Start proc 11676:eu.siacs.conversations/u0a155 for activity eu.siacs.conversations/.ui.ConversationActivity
05-10 14:41:29.738 11676 11676 I s.conversation: The ClassLoaderContext is a special shared library.
05-10 14:41:29.814   576   771 I ActivityManager: START u0 {cmp=eu.siacs.conversations/.ui.ConversationsActivity} from uid 10155
05-10 14:41:29.858 11676 11676 E ToneGenerator: Unable to marshal AudioFlinger
05-10 14:41:29.858 11676 11676 E ToneGenerator: ToneGenerator init failed
05-10 14:41:29.859 11676 11676 D AndroidRuntime: Shutting down VM
05-10 14:41:29.860 11676 11676 E AndroidRuntime: FATAL EXCEPTION: main
05-10 14:41:29.860 11676 11676 E AndroidRuntime: Process: eu.siacs.conversations, PID: 11676
05-10 14:41:29.860 11676 11676 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate service eu.siacs.conversations.services.XmppConnectionService: java.lang.RuntimeException: Init failed
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3557)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:200)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: Caused by: java.lang.RuntimeException: Init failed
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.media.ToneGenerator.native_setup(Native Method)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.media.ToneGenerator.<init>(ToneGenerator.java:746)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at eu.siacs.conversations.xmpp.jingle.ToneManager.<init>(ToneManager.java:24)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at eu.siacs.conversations.xmpp.jingle.JingleConnectionManager.<init>(JingleConnectionManager.java:54)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at eu.siacs.conversations.services.XmppConnectionService.<init>(XmppConnectionService.java:231)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.support.v4.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3552)
05-10 14:41:29.860 11676 11676 E AndroidRuntime: 	... 8 more
05-10 14:41:29.866   576   621 I ActivityManager: Showing crash dialog for package eu.siacs.conversations u0
05-10 14:41:29.903   576  4760 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
05-10 14:41:29.904   576  4760 D vndksupport: Loading /vendor/lib/hw/gralloc.msm8974.so from current namespace instead of sphal namespace.
05-10 14:41:30.319   576   620 W ActivityManager: Activity pause timeout for ActivityRecord{3d5875f u0 eu.siacs.conversations/.ui.ConversationActivity t3761 f}

````

**Comment by tuxayo** [comment]
It works!

Thanks a lot @iNPUTmice for fix :green_heart: . Even if it would be sad, I would have understood to not fix something for device with unusual hardware damage. But no, it was fixed. Thanks again!
