### ISSUE TITLE
 XMPP/Jingle calling between Conversations (Android) and Pidgin (Linux)

### ISSUE THREAD

**Issue by merge** [iNPUTmice/Conversations#3725]
#### General information

* **Version:** 2.8.2+fcr
* **Device:** Nexus 5X
* **Android Version:**  LineageOS 15.1 (Android 8.1.0)
* **Server name:** jabber.at
* **Server software:**
* **Installed server modules:**
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Open Pidgin with different XMPP Account on a Linux desktop
2. No Call capability is shown in Conversations
3. Call capability is shown in Pidgin but calling fails very early

#### Expected result

XMPP/Jingle audio calling working between Conversations (Android) and Pidgin (Linux)

#### Actual result

Audio (or Video) calling doesn't work. It works very well when *both* Accounts use Pidgin (Linux) or *both* use Conversations.

#### Debug output

Logs when trying to call (audio) from Pidgin are below (Pidgin at least "discovers" that is could call)

```
05-12 14:36:39.536 D/conversations(24312): martink@jabber.at: packet delivered to JingleRtpConnection
05-12 14:36:39.541 D/conversations(24312): martink@jabber.at: improperly formatted contents
05-12 14:36:39.541 D/conversations(24312): java.lang.SecurityException: Use of DTLS-SRTP (XEP-0320) is required for content audio-session
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.jingle.RtpContentMap.requireDTLSFingerprint(RtpContentMap.java:81)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.receiveSessionInitiate(JingleRtpConnection.java:285)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.deliverPacket(JingleRtpConnection.java:167)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.jingle.JingleConnectionManager.deliverPacket(JingleConnectionManager.java:110)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.services.XmppConnectionService.lambda$createConnection$11$XmppConnectionService(XmppConnectionService.java:1345)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$VYN9drkH9aobUCuwT-F_1u6C7v8.onJinglePacketReceived(Unknown Source:2)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:729)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:636)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:484)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:376)
05-12 14:36:39.541 D/conversations(24312): 	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:455)
05-12 14:36:39.541 D/conversations(24312): 	at java.lang.Thread.run(Thread.java:764)
05-12 14:36:39.543 D/conversations(24312): martink@jabber.at: transitioned into TERMINATED_APPLICATION_FAILURE
05-12 14:36:39.577 D/conversations(24312): ForegroundService: on
05-12 14:36:39.594 D/conversations(24312): <iq type="set"><jingle sid="purple2093832" action="session-terminate" xmlns="urn:xmpp:jingle:1"><reason><security-error/><text>Use of DTLS-SRTP (XEP-0320) is required for content audio-session</text></reason></jingle></iq>
```

**Comment by iNPUTmice** [comment]
Pidgin does not support encryption via DTLS-SRTP. Please open an issue on Pidgin. We have to plans to support unencrypted calls. (FWIW the stack trace you posted actually says this.)

**Comment by merge** [comment]
thanks for clarifying so quickly
