### ISSUE TITLE
not providing `ufrag` on a jingle <transport> causes calls to fail

### ISSUE THREAD

**Issue by eeeeeta** [iNPUTmice/Conversations#3739]
On [line 149 of SessionDescription.java](https://github.com/iNPUTmice/Conversations/blob/f7a0d2031a815a3a3478bc87aa15eee4a60b6971/src/main/java/eu/siacs/conversations/xmpp/jingle/SessionDescription.java#L149), the `ufrag` attribute on a jingle `<transport>` is checked for whitespace even if it is null (i.e. not provided by the other party). This causes the conversion to SDP to fail, and the call to be terminated:

```
05-18 16:13:47.472 23548 23548 D conversations: eta@theta.eu.org: unable convert offer from session-initiate to SDP
05-18 16:13:47.472 23548 23548 D conversations: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
05-18 16:13:47.472 23548 23548 D conversations: 	at com.google.common.base.CharMatcher.indexIn(CharMatcher.java:560)
05-18 16:13:47.472 23548 23548 D conversations: 	at com.google.common.base.CharMatcher.indexIn(CharMatcher.java:541)
05-18 16:13:47.472 23548 23548 D conversations: 	at com.google.common.base.CharMatcher.matchesNoneOf(CharMatcher.java:527)
05-18 16:13:47.472 23548 23548 D conversations: 	at com.google.common.base.CharMatcher.matchesAnyOf(CharMatcher.java:493)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.xmpp.jingle.SessionDescription.checkNoWhitespace(SessionDescription.java:274)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.xmpp.jingle.SessionDescription.of(SessionDescription.java:149)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.sendSessionAccept(JingleRtpConnection.java:405)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.acceptCallFromSessionInitialized(JingleRtpConnection.java:971)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.acceptCall(JingleRtpConnection.java:855)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.ui.RtpSessionActivity.checkRecorderAndAcceptCall(RtpSessionActivity.java:165)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.ui.RtpSessionActivity.requestPermissionsAndAcceptCall(RtpSessionActivity.java:158)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.ui.RtpSessionActivity.onBackendConnected(RtpSessionActivity.java:279)
05-18 16:13:47.472 23548 23548 D conversations: 	at eu.siacs.conversations.ui.XmppActivity$1.onServiceConnected(XmppActivity.java:112)
05-18 16:13:47.472 23548 23548 D conversations: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1739)
05-18 16:13:47.472 23548 23548 D conversations: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1771)
05-18 16:13:47.472 23548 23548 D conversations: 	at android.os.Handler.handleCallback(Handler.java:873)
05-18 16:13:47.472 23548 23548 D conversations: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-18 16:13:47.472 23548 23548 D conversations: 	at android.os.Looper.loop(Looper.java:193)
05-18 16:13:47.472 23548 23548 D conversations: 	at android.app.ActivityThread.main(ActivityThread.java:6923)
05-18 16:13:47.472 23548 23548 D conversations: 	at java.lang.reflect.Method.invoke(Native Method)
05-18 16:13:47.472 23548 23548 D conversations: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-18 16:13:47.472 23548 23548 D conversations: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
05-18 16:13:47.472 23548 23548 D conversations: eta@theta.eu.org: transitioned into TERMINATED_APPLICATION_FAILURE
```

**Comment by iNPUTmice** [comment]
The `ufrag` attribute is a MUST in the spec.
