### ISSUE TITLE
Conversations v2.8.7 media call compatibility with aTalk v2.3.0

### ISSUE THREAD

**Issue by cmeng-git** [iNPUTmice/Conversations#3788]
#### General information
* **Version:** 2.8.7-beta.2+fcd
* **Device:** Samsung Note-10 (API-29) / Samsung Note-5 (API-21)
* **Android Version:**  Android 10 / Andorid-5
* **Server name:** atalk.sytes.net self hosted
* **Server software:** ejabberd 18.09
* **Conversations source:** self build (2.8.7-beta.2+fcd)

Below are the media call compatibility test observations between Conversations v2.8.7 and aTalk 2.3.0. Appreciate if your team can enlighten on the observations/results:
Note: So far, there are no observable differences in the test results of the call setup between Note-10 and Note-5. Both devices are installed with Conversations and aTalk, and either can be caller or callpeer of Conversations or aTalk.

Below are the implement differences between the two: 
```
     1. Conversations implementations:
     * a. transport-info's are sent per media after session-initiate stanza;
     * b. transport-info's are sent per media after session-accept stanza;

     2. aTalk implementations:
     * a. transport-info's are embedded within session-initiate stanza;
     * b. transport-info's are sent per media prior to session-accept stanza;
```

### Audio call:
1. aTalk to Conversations - OK
2. Conversations to aTalk - Both stuck in 'Connecting' call state.

### Video call:
1. aTalk to Conversations 
a. Audio call setup correctly at the start.
b. Local video previews are shown briefly, then Conversations crashes immediately after that.

2. Conversations to aTalk
a. Both stuck in 'Connecting' call state, with local video preview being shown.

### Other observations:
1. It seems that the video call issue is due to the fact that aTalk send the \<transport-info/> for the medias prior to \<session-accept/>; Conversations seems not to like this.

2. If I remember correctly, audio call was working with Conversations v2.8.5. However there was a long delay ~5s before aTalk receive the audio stream.

3.  h264 codec is not compatible with the two. Look like aTalk cannot support 
\<parameter name='packetization-mode' value='1'/>; Conversations crashes if h264 codec is used.

4. You may also like to refer to aTalk release note for all changes made so as to be compatible with Conversations.
[Release Notes](https://github.com/cmeng-git/atalk-android/blob/master/aTalk/ReleaseNotes.txt)

**Comment by iNPUTmice** [comment]
> It seems that the video call issue is due to the fact that aTalk send the <transport-info/> for the medias prior to <session-accept/>; Conversations seems not to like this.

This is tracked here:  #3790

> b. Local video previews are shown briefly, then Conversations crashes immediately after that.

If you have a stack trace for that crash I'd like to see it.

**Comment by cmeng-git** [comment]
> If you have a stack trace for that crash I'd like to see it.

Actually aTalk source is available online: https://github.com/cmeng-git/atalk-android
You many download and build a debug version to see all the observations that I have reported.

You may also need aTalk later to verify the changes made in Conversations.

**Comment by iNPUTmice** [comment]
```
06-22 16:46:51.266 I/org.webrtc.Logging( 4054): AndroidVideoDecoder: ctor name: c2.qti.vp8.decoder type: VP8 color format: 19 context: org.webrtc.EglBase14Impl$Context@d073b8e
06-22 16:46:51.267 W/System.err( 4054): java.lang.IllegalArgumentException: No enum constant org.webrtc.VideoCodecMimeType.h264
06-22 16:46:51.267 W/System.err( 4054): 	at java.lang.Enum.valueOf(Enum.java:257)
06-22 16:46:51.267 W/System.err( 4054): 	at org.webrtc.VideoCodecMimeType.valueOf(VideoCodecMimeType.java:14)
06-22 16:46:51.267 W/System.err( 4054): 	at org.webrtc.MediaCodecVideoDecoderFactory.createDecoder(MediaCodecVideoDecoderFactory.java:49)
06-22 16:46:51.268 W/System.err( 4054): 	at org.webrtc.HardwareVideoDecoderFactory.createDecoder(HardwareVideoDecoderFactory.java:18)
06-22 16:46:51.268 W/System.err( 4054): 	at org.webrtc.DefaultVideoDecoderFactory.createDecoder(DefaultVideoDecoderFactory.java:44)
06-22 16:46:51.268 E/rtc     ( 4054): 
06-22 16:46:51.268 E/rtc     ( 4054): 
06-22 16:46:51.268 E/rtc     ( 4054): #
06-22 16:46:51.268 E/rtc     ( 4054): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../../root/src/sdk/android/src/jni/jni_generator_helper.h, line 94
06-22 16:46:51.268 E/rtc     ( 4054): # last system error: 0
06-22 16:46:51.268 E/rtc     ( 4054): # Check failed: !env->ExceptionCheck()
06-22 16:46:51.268 E/rtc     ( 4054): # 
06-22 16:46:51.268 F/libc    ( 4054): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4273 (worker_thread -), pid 4054 (s.conversations)
06-22 16:46:51.310 E/DEBUG   ( 4428): failed to readlink /proc/4273/fd/115: No such file or directory
06-22 16:46:51.353 I/crash_dump64( 4428): obtaining output fd from tombstoned, type: kDebuggerdTombstone
06-22 16:46:51.354 I//system/bin/tombstoned( 1067): received crash request for pid 4273
06-22 16:46:51.354 I/crash_dump64( 4428): performing dump of process 4054 (target tid = 4273)
06-22 16:46:51.364 F/DEBUG   ( 4428): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-22 16:46:51.364 F/DEBUG   ( 4428): Build fingerprint: 'google/sargo/sargo:10/QQ3A.200605.002/6416773:user/release-keys'
06-22 16:46:51.364 F/DEBUG   ( 4428): Revision: 'MP1.0'
06-22 16:46:51.364 F/DEBUG   ( 4428): ABI: 'arm64'
06-22 16:46:51.364 F/DEBUG   ( 4428): Timestamp: 2020-06-22 16:46:51+0200
06-22 16:46:51.364 F/DEBUG   ( 4428): pid: 4054, tid: 4273, name: worker_thread -  >>> eu.siacs.conversations <<<
06-22 16:46:51.364 F/DEBUG   ( 4428): uid: 10238
06-22 16:46:51.364 F/DEBUG   ( 4428): signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
06-22 16:46:51.364 F/DEBUG   ( 4428):     x0  0000000000000000  x1  00000000000010b1  x2  0000000000000006  x3  0000007c57797ee0
06-22 16:46:51.364 F/DEBUG   ( 4428):     x4  feff1f220928276a  x5  feff1f220928276a  x6  feff1f220928276a  x7  7f7f7f7f7f7f7f7f
06-22 16:46:51.364 F/DEBUG   ( 4428):     x8  00000000000000f0  x9  6b90fb964e9368b4  x10 0000000000000001  x11 0000000000000000
06-22 16:46:51.364 F/DEBUG   ( 4428):     x12 fffffff0fffffbdf  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
06-22 16:46:51.364 F/DEBUG   ( 4428):     x16 0000007cea6808c0  x17 0000007cea65e0c0  x18 0000007be9a80000  x19 0000000000000fd6
06-22 16:46:51.364 F/DEBUG   ( 4428):     x20 00000000000010b1  x21 00000000ffffffff  x22 0000007c0d502438  x23 0000007c5bcfe7c0
06-22 16:46:51.364 F/DEBUG   ( 4428):     x24 0000007bfa481d18  x25 0000007bfa481cb0  x26 0000000000000040  x27 000000000000002f
06-22 16:46:51.364 F/DEBUG   ( 4428):     x28 0000007bf5936720  x29 0000007c57797f80
06-22 16:46:51.364 F/DEBUG   ( 4428):     sp  0000007c57797ec0  lr  0000007cea612f48  pc  0000007cea612f74
06-22 16:46:51.366 F/DEBUG   ( 4428): 
06-22 16:46:51.366 F/DEBUG   ( 4428): backtrace:
06-22 16:46:51.366 F/DEBUG   ( 4428):       #00 pc 0000000000081f74  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 8de865099c99977483c8947f9b7937e9)
06-22 16:46:51.366 F/DEBUG   ( 4428):       #01 pc 00000000002577b4  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #02 pc 00000000002373c8  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #03 pc 00000000002372f0  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #04 pc 00000000003d0474  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #05 pc 000000000056e5a0  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #06 pc 00000000004fd4fc  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #07 pc 00000000004f6450  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #08 pc 00000000004f6094  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #09 pc 00000000004fb2cc  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #10 pc 000000000064d598  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #11 pc 00000000002376fc  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #12 pc 00000000002514a8  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #13 pc 0000000000250564  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #14 pc 0000000000251964  /data/app/eu.siacs.conversations-5yswRKcOfA9ZR5wP_d4VVg==/lib/arm64/libjingle_peerconnection_so.so
06-22 16:46:51.366 F/DEBUG   ( 4428):       #15 pc 00000000000e10a0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 8de865099c99977483c8947f9b7937e9)
06-22 16:46:51.366 F/DEBUG   ( 4428):       #16 pc 0000000000083ab0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 8de865099c99977483c8947f9b7937e9)
```

**Comment by iNPUTmice** [comment]
When attempting to call aTalk from Conversations I’m getting errors like these:
```xml
 <iq type="set" xml:lang="en-US" xmlns="jabber:client" id="4KG55-54" from="i…/atalk" to="…/Conversations.7LSk">
  <jingle sid="+k1JlUHbFbOuNXmLGO2l3w" action="session-terminate" xmlns="urn:xmpp:jingle:1">
    <reason xmlns="urn:xmpp:jingle:1">
      <incompatible-parameters xmlns="urn:xmpp:jingle:1"/>
      <text xmlns="urn:xmpp:jingle:1">
        Error: Attempt to invoke virtual method &apos;org.atalk.service.neomedia.device.MediaDevice net.java.sip.communicator.service.protocol.media.MediaAwareCall.getDefaultDevice(org.atalk.service.neomedia.MediaType)&apos; on a null object reference
      </text>
    </reason>
  </jingle>
</iq>
```
Actually a bunch of them. aTalk seems to want to terminate the session like 6 different times.
aTalks also sends a session-info/ringing after it itself has already terminated the session.
That makes it a little difficult to verify the transport-info issue because that only happens if Conversations initiate the calls. But due to the crashes I’m not even getting to this point.

**Comment by cmeng-git** [comment]
Please pull in a new aTalk update that fixes double session-accept being sent? However I believe this should not be the cause of the problem in your current testing.

Not all aTalk codecs are fully tested. Please check codec selection on aTalk; put Opus audio codec and VP8 as first choice in the codec settings. Not sure if the problem you observe is due to codec selection. Do not use h264, it seems this will cause Conversations to crash. 

All my tests were carried out between two Samsung devices i.e. Note-10 and Note-5. So far I do not have the problem that you have observed. Seem like the problem is due to codec incompatibility (from Conversations log) ??? This causes aTalk sending the 'session-terminte" stanza after finding no compatible codec to handle the media.

On the Samsung Note-10 device, I see the following  VP8 codecs implementations i.e.
a. OMX.Exynos.VP8 dec
b. OMX.Exynos.VP8 Encoder
c. OMX.google.vp8.decoder
d. c2.android.vp8.encoder

Look like your device has a different VP8 codec i.e. c2.qti.vp8.decoder

When making call from Conversations to aTalk, aTalk debug log shows. The problem point to media channel not setup properly:
```
2020-06-23 08:19:19.512 23001-31593/org.atalk.android E/(TransportManager.java:443)#sendHolePunchPacket: Error cannot send to remote peer for media: AUDIO ; MediaStreamTarget with dataAddress null and controlAddress null
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.InetAddress java.net.InetSocketAddress.getAddress()' on a null object reference
        at net.java.sip.communicator.service.protocol.media.TransportManager.sendHolePunchPacket(TransportManager.java:432)
        at net.java.sip.communicator.service.protocol.media.CallPeerMediaHandler.sendHolePunchPacket(CallPeerMediaHandler.java:1332)
        at net.java.sip.communicator.service.protocol.media.CallPeerMediaHandler.start(CallPeerMediaHandler.java:1582)
        at net.java.sip.communicator.impl.protocol.jabber.CallPeerMediaHandlerJabberImpl.start(CallPeerMediaHandlerJabberImpl.java:1598)
        at net.java.sip.communicator.impl.protocol.jabber.CallPeerJabberImpl.answer(CallPeerJabberImpl.java:198)
        at net.java.sip.communicator.impl.protocol.jabber.OperationSetVideoTelephonyJabberImpl.answerVideoCallPeer(OperationSetVideoTelephonyJabberImpl.java:126)
        at net.java.sip.communicator.service.protocol.AbstractOperationSetBasicAutoAnswer$AutoAnswerThread.run(AbstractOperationSetBasicAutoAnswer.java:216)
        at java.lang.Thread.run(Thread.java:919)

2020-06-23 08:19:19.779 23001-31593/org.atalk.android E/(TransportManager.java:443)#sendHolePunchPacket: Error cannot send to remote peer for media: VIDEO ; MediaStreamTarget with dataAddress null and controlAddress null
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.InetAddress java.net.InetSocketAddress.getAddress()' on a null object reference
        at net.java.sip.communicator.service.protocol.media.TransportManager.sendHolePunchPacket(TransportManager.java:432)
        at net.java.sip.communicator.service.protocol.media.CallPeerMediaHandler.sendHolePunchPacket(CallPeerMediaHandler.java:1332)
        at net.java.sip.communicator.service.protocol.media.CallPeerMediaHandler.start(CallPeerMediaHandler.java:1604)
        at net.java.sip.communicator.impl.protocol.jabber.CallPeerMediaHandlerJabberImpl.start(CallPeerMediaHandlerJabberImpl.java:1598)
        at net.java.sip.communicator.impl.protocol.jabber.CallPeerJabberImpl.answer(CallPeerJabberImpl.java:198)
        at net.java.sip.communicator.impl.protocol.jabber.OperationSetVideoTelephonyJabberImpl.answerVideoCallPeer(OperationSetVideoTelephonyJabberImpl.java:126)
        at net.java.sip.communicator.service.protocol.AbstractOperationSetBasicAutoAnswer$AutoAnswerThread.run(AbstractOperationSetBasicAutoAnswer.java:216)
        at java.lang.Thread.run(Thread.java:919)

```

**Comment by iNPUTmice** [comment]
The related issue on the aTalk tracker has been closed and apparently it is working now. https://github.com/cmeng-git/atalk-android/issues/140
