### ISSUE TITLE
Restoring backup does not work

### ISSUE THREAD

**Issue by ericschdt** [iNPUTmice/Conversations#3942]
#### General information

* **Version:** 2.9.1
* **Device:** Pixel 4a
* **Android Version:**  GrapheneOS 
* **Conversations source:** F-Droid

#### Steps to reproduce

1. Logout on phone A with Conversations 2.9.1
2. Backup
3. Put Backup on new phone B in the primary/Documents folder
4. Open Conversations 2.9.1 and pick the *.ceb file for restoring

#### Actual result

Conversations' notification shows a progressbar. At the end it says "Import failed" and "App does not respond".

#### Debug output

````
adb -d logcat -v time -s conversations
- waiting for device -
--------- beginning of system
--------- beginning of crash
--------- beginning of main
12-08 21:08:32.504 D/conversations(23032): attempting to import content://com.android.externalstorage.documents/document/primary%3ADocuments%2FConversations%2FBackUps%2Ferics%40foo.bar.ceb
12-08 21:10:28.361 D/conversations(24973): ForegroundService: on
12-08 21:10:28.408 D/conversations(24973): initializing database...
12-08 21:10:28.408 D/conversations(24973): restoring accounts...
12-08 21:10:28.419 D/conversations(24973): restoring conversations...
12-08 21:10:28.420 D/conversations(24973): finished restoring conversations in 1ms
12-08 21:10:28.420 D/conversations(24973): restoring roster...
12-08 21:10:28.421 D/conversations(24973): starting file observer
12-08 21:10:28.421 D/conversations(24973): restoring messages...
12-08 21:10:28.421 D/conversations(24973): update unread count to 0
12-08 21:10:28.421 D/conversations(24973): start merging phone contacts with roster
12-08 21:10:28.421 D/conversations(24973): finished merging phone contacts
12-08 21:10:28.426 D/conversations(24973): updated dynamic shortcuts
12-08 21:10:28.427 D/conversations(24973): finished restoring messages in 6ms
12-08 21:10:28.428 D/conversations(24973): ForegroundService: on
12-08 21:10:28.431 D/conversations(24973): ForegroundService: off
12-08 21:10:28.492 D/conversations(24973): resetting all attempt counts
12-08 21:10:28.496 D/conversations(24973): found 0 changed files on start up. total=0. (1ms)
````

**Comment by ericschdt** [comment]
Seemed to have been a permission issue. GPS, Camera, Microphone and Contacts weren't granted before. After I granted those too, it worked! Maybe Conversations should prompt for permission for those too if they are required for the backup.

**Comment by centertivevier** [comment]
> #### General information
> 
>     * **Version:** 2.9.5
> 
>     * **Device:** OnePlus 7 Pro
> 
>     * **Android Version:**  LineageOS 17.1
> 
>     * **Conversations source:** F-Droid
> 
> 
> #### Steps to reproduce
> 
>     1. Logout on phone A with Conversations 2.9.5
> 
>     2. Backup
> 
>     3. Put Backup on new phone B in the primary/Documents folder
> 
>     4. Open Conversations 2.9.5 and pick the *.ceb file for restoring

Conversations' notification shows a progressbar. At the end it says "cant restore the backup"

`
adb -d logcat -v time -s conversations
01-30 15:36:22.878 D/conversations( 7071): action: null
01-30 15:36:22.888 D/conversations( 7071): ConversationsOverviewFragment.onStart()
01-30 15:36:22.889 D/conversations( 7071): ConversationsOverviewFragment.onResume()
01-30 15:36:22.952 D/conversations( 7071): ForegroundService: on
01-30 15:36:22.985 D/conversations( 7071): initializing database...
01-30 15:36:22.986 D/conversations( 7071): restoring accounts...
01-30 15:36:22.990 D/conversations( 7071): restoring conversations...
01-30 15:36:22.991 D/conversations( 7071): finished restoring conversations in 0ms
01-30 15:36:22.991 D/conversations( 7071): restoring roster...
01-30 15:36:22.992 D/conversations( 7071): restoring messages...
01-30 15:36:22.992 D/conversations( 7071): update unread count to 0
01-30 15:36:22.992 D/conversations( 7071): starting file observer
01-30 15:36:22.993 D/conversations( 7071): 1 remaining tasks on executor 'FileAdding'
01-30 15:36:22.996 D/conversations( 7071): finished restoring messages in 4ms
01-30 15:36:23.002 D/conversations( 7071): ForegroundService: on
01-30 15:36:23.007 D/conversations( 7071): ForegroundService: off
01-30 15:36:23.020 D/conversations( 7071): start merging phone contacts with roster
01-30 15:36:23.020 D/conversations( 7071): finished merging phone contacts
01-30 15:36:23.025 D/conversations( 7071): updated dynamic shortcuts
01-30 15:36:23.028 D/conversations( 7071): found 0 changed files on start up. total=0. (1ms)
01-30 15:36:23.037 D/conversations( 7071): resetting all attempt counts
01-30 15:36:23.038 D/conversations( 7071): app switched into foreground
01-30 15:36:23.048 D/conversations( 7071): ConversationsOverviewFragment.onPause()
01-30 15:36:23.274 D/conversations( 7071): app switched into background
01-30 15:36:23.287 D/conversations( 7071): ConversationsOverviewFragment.onDestroyView()
01-30 15:36:23.287 D/conversations( 7071): ConversationsOverviewFragment.onDestroy()
01-30 15:36:33.090 D/conversations( 7071): directory not found: /storage/emulated/0/Quicksy/Backup
01-30 15:36:33.090 D/conversations( 7071): directory not found: /storage/emulated/0/Conversations/Backup
01-30 15:36:53.081 D/conversations( 7071): EventReceiver ignored action eu.siacs.conversations.POST_CONNECTIVITY_CHANGE
01-30 15:42:42.842 D/conversations( 7071): directory not found: /storage/emulated/0/Quicksy/Backup
01-30 15:42:42.842 D/conversations( 7071): directory not found: /storage/emulated/0/Conversations/Backup
01-30 15:44:17.445 D/conversations( 7071): action: null
01-30 15:44:17.451 D/conversations( 7071): ConversationsOverviewFragment.onStart()
01-30 15:44:17.451 D/conversations( 7071): ConversationsOverviewFragment.onResume()
01-30 15:44:17.476 D/conversations( 7071): app switched into foreground
01-30 15:44:17.503 D/conversations( 7071): ConversationsOverviewFragment.onPause()
01-30 15:44:17.577 D/conversations( 7071): app switched into background
01-30 15:44:17.578 D/conversations( 7071): ConversationsOverviewFragment.onDestroyView()
01-30 15:44:17.578 D/conversations( 7071): ConversationsOverviewFragment.onDestroy()
01-30 15:45:05.680 D/conversations( 7078): action: null
01-30 15:45:05.689 D/conversations( 7078): ConversationsOverviewFragment.onStart()
01-30 15:45:05.689 D/conversations( 7078): ConversationsOverviewFragment.onResume()
01-30 15:45:05.785 D/conversations( 7078): ForegroundService: on
01-30 15:45:05.813 D/conversations( 7078): initializing database...
01-30 15:45:05.813 D/conversations( 7078): restoring accounts...
01-30 15:45:05.846 D/conversations( 7078): restoring conversations...
01-30 15:45:05.847 D/conversations( 7078): finished restoring conversations in 0ms
01-30 15:45:05.847 D/conversations( 7078): restoring roster...
01-30 15:45:05.848 D/conversations( 7078): restoring messages...
01-30 15:45:05.848 D/conversations( 7078): update unread count to 0
01-30 15:45:05.848 D/conversations( 7078): start merging phone contacts with roster
01-30 15:45:05.849 D/conversations( 7078): finished merging phone contacts
01-30 15:45:05.850 D/conversations( 7078): finished restoring messages in 3ms
01-30 15:45:05.853 D/conversations( 7078): updated dynamic shortcuts
01-30 15:45:05.853 D/conversations( 7078): ForegroundService: on
01-30 15:45:05.860 D/conversations( 7078): ForegroundService: off
01-30 15:45:05.896 D/conversations( 7078): resetting all attempt counts
01-30 15:45:05.898 D/conversations( 7078): app switched into foreground
01-30 15:45:05.913 D/conversations( 7078): ConversationsOverviewFragment.onPause()
01-30 15:45:06.089 D/conversations( 7078): app switched into background
01-30 15:45:06.090 D/conversations( 7078): ConversationsOverviewFragment.onDestroyView()
01-30 15:45:06.091 D/conversations( 7078): ConversationsOverviewFragment.onDestroy()
01-30 15:45:09.943 D/conversations( 7078): restarting file observer
01-30 15:45:09.996 D/conversations( 7078): found 0 changed files on start up. total=0. (1ms)
01-30 15:45:10.003 D/conversations( 7078): directory not found: /storage/emulated/0/Quicksy/Backup
01-30 15:45:10.004 D/conversations( 7078): directory not found: /storage/emulated/0/Conversations/Backup
01-30 15:45:12.999 D/conversations( 7078): attempting to import content://com.android.externalstorage.documents/backup.ceb
01-30 15:45:13.059 D/conversations( 7078): directory not found: /storage/emulated/0/Quicksy/Backup
01-30 15:45:13.059 D/conversations( 7078): directory not found: /storage/emulated/0/Conversations/Backup
01-30 15:45:35.901 D/conversations( 7078): EventReceiver ignored action eu.siacs.conversations.POST_CONNECTIVITY_CHANGE
01-30 15:45:37.073 D/conversations( 7078): importing backup from content://com.android.externalstorage.documents/backup.ceb
01-30 15:45:37.090 D/conversations( 7078): BackupFileHeader{app='Conversations', jid=account, timestamp=1612016084925, iv=XXX, salt=XXXX}
01-30 15:45:37.124 D/conversations( 7078): error restoring backup content://com.android.externalstorage.documents/backup.ceb
01-30 15:45:37.124 D/conversations( 7078): android.database.sqlite.SQLiteException: unrecognized token: "'All Chats are in the log seeing from the backup'"
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1805)
01-30 15:48:23.741 D/conversations( 9045): 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1733)
01-30 15:48:23.741 D/conversations( 9045): 	at eu.siacs.conversations.services.ImportBackupService.importBackup(ImportBackupService.java:253)
01-30 15:48:23.741 D/conversations( 9045): 	at eu.siacs.conversations.services.ImportBackupService.lambda$onStartCommand$0(ImportBackupService.java:107)
01-30 15:48:23.741 D/conversations( 9045): 	at eu.siacs.conversations.services.ImportBackupService.lambda$onStartCommand$0$ImportBackupService(Unknown Source:0)
01-30 15:48:23.741 D/conversations( 9045): 	at eu.siacs.conversations.services.-$$Lambda$ImportBackupService$_Gblybgouv1Yt7P2F13nA3J9Xfw.run(Unknown Source:6)
01-30 15:48:23.741 D/conversations( 9045): 	at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
01-30 15:48:23.741 D/conversations( 9045): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-30 15:48:23.741 D/conversations( 9045): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-30 15:48:23.741 D/conversations( 9045): 	at java.lang.Thread.run(Thread.java:919)
`

Anyone a idea? All Permissions are the same from the old one.
