### ISSUE TITLE
2.9.2 crashes while app foreground user inactive

### ISSUE THREAD

**Issue by underhandedness** [iNPUTmice/Conversations#3951]
#### General information

* **Version:** 2.9.2
* **Device:** samsung
* **Android Version:**  kitkat
* **Server name:** conversations.im (and others, none self)

#### Steps to reproduce

1. open app
2. send message
3. return to list of chats
4. set phone down
5. wait more than 2 minutes
6. interact with app
7. crash
8. reopen app
9. submit error report

1.5 years of versions without a hiccup

F-droid build

#### Expected result

What is the expected output? 

not crashing

#### Actual result

What do you see instead?

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
<<< log_count = 21 >>>
[12-22 01:59:15.508 28810:28810 E/dalvikvm]
>>>>> eu.siacs.conversations [ userId:0 | appId:10256 ]

[12-22 01:59:15.678 28810:28810 W/XPrivacy]
Hooking package=eu.siacs.conversations

[12-22 01:59:15.908 28810:28810 E/dalvikvm]
Could not find class 'android.graphics.pdf.PdfRenderer', referenced from method eu.siacs.conversations.persistance.FileBackend.getPdfDocumentDimensions

[12-22 01:59:15.908 28810:28810 W/dalvikvm]
VFY: unable to resolve new-instance 270 (Landroid/graphics/pdf/PdfRenderer;) in Leu/siacs/conversations/persistance/FileBackend;

[12-22 01:59:15.908 28810:28810 E/dalvikvm]
Could not find class 'android.graphics.pdf.PdfRenderer', referenced from method eu.siacs.conversations.persistance.FileBackend.renderPdfDocument

[12-22 01:59:15.908 28810:28810 W/dalvikvm]
VFY: unable to resolve new-instance 270 (Landroid/graphics/pdf/PdfRenderer;) in Leu/siacs/conversations/persistance/FileBackend;

[12-22 01:59:15.938 28810:28810 E/dalvikvm]
Could not find class 'android.content.pm.ShortcutInfo', referenced from method eu.siacs.conversations.services.ShortcutService.contactExists

[12-22 01:59:15.938 28810:28810 W/dalvikvm]
VFY: unable to resolve check-cast 156 (Landroid/content/pm/ShortcutInfo;) in Leu/siacs/conversations/services/ShortcutService;

[12-22 01:59:15.938 28810:28810 E/dalvikvm]
Could not find class 'android.content.pm.ShortcutInfo$Builder', referenced from method eu.siacs.conversations.services.ShortcutService.getShortcutInfo

[12-22 01:59:15.938 28810:28810 W/dalvikvm]
VFY: unable to resolve new-instance 155 (Landroid/content/pm/ShortcutInfo$Builder;) in Leu/siacs/conversations/services/ShortcutService;

[12-22 01:59:15.938 28810:28810 E/dalvikvm]
Could not find class 'android.content.pm.ShortcutManager', referenced from method eu.siacs.conversations.services.ShortcutService.refreshImpl

[12-22 01:59:15.938 28810:28810 W/dalvikvm]
VFY: unable to resolve const-class 157 (Landroid/content/pm/ShortcutManager;) in Leu/siacs/conversations/services/ShortcutService;

[12-22 01:59:15.938 28810:28810 E/dalvikvm]
Could not find class 'android.content.pm.ShortcutManager', referenced from method eu.siacs.conversations.services.ShortcutService.createShortcut

[12-22 01:59:15.938 28810:28810 W/dalvikvm]
VFY: unable to resolve const-class 157 (Landroid/content/pm/ShortcutManager;) in Leu/siacs/conversations/services/ShortcutService;

[12-22 01:59:15.938 28810:28810 E/dalvikvm]
Could not find class 'android.content.pm.ShortcutManager', referenced from method eu.siacs.conversations.services.ShortcutService.report

[12-22 01:59:15.938 28810:28810 W/dalvikvm]
VFY: unable to resolve const-class 157 (Landroid/content/pm/ShortcutManager;) in Leu/siacs/conversations/services/ShortcutService;

[12-22 01:59:19.748 28810:28836 E/dalvikvm]
Could not find class 'javax.net.ssl.SNIHostName', referenced from method eu.siacs.conversations.utils.SSLSocketHelper.setHostnameNougat

[12-22 01:59:19.748 28810:28836 W/dalvikvm]
VFY: unable to resolve new-instance 4589 (Ljavax/net/ssl/SNIHostName;) in Leu/siacs/conversations/utils/SSLSocketHelper;

[12-22 01:59:26.668 28810:28832 W/conversations]
AxolotlService (x@blabber.im): Reflected omemo message received

[12-22 01:59:26.848 28810:28832 W/conversations]
AxolotlService (x@blabber.im): Reflected omemo message received

[12-22 02:07:46.029 1057:1725 W/NotificationService]
Toast already cancelled. pkg=eu.siacs.conversations callback=android.app.ITransientNotification$Stub$Proxy@45061868


````

crash error

Version: 2.9.2+fcr(402)
Last Update: 2020-12-18
SHA-1: 20:ab:18:ba:4d:49:1d:f1:b7:bf:50:51:be:1f:e2:6e:b7:56:27:73

java.lang.NullPointerException
	at eu.siacs.conversations.ui.ConversationFragment.onCreateOptionsMenu(ConversationFragment.java:989)
	at android.app.Fragment.performCreateOptionsMenu(Fragment.java:1780)
	at android.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:1933)
	at android.app.Activity.onCreatePanelMenu(Activity.java:2747)
	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:378)
	at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2549)
	at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5748)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by licaon-kter** [comment]
Can you disable Xposed, reboot, retest?
