### ISSUE TITLE
jingle: unexpected session-terminate reason for invalid session-initiate request

### ISSUE THREAD

**Issue by rhymecat** [iNPUTmice/Conversations#3956]
#### General information

* **Version:** 2.9.2
* **Conversations source:** F-Droid

#### Steps to reproduce

- I'm trying to establish a call between Conversations and a broken / unfinished client.
- Conversations is receiving an invalid `session-initiate` ([`transport`](https://xmpp.org/extensions/xep-0176.html#protocol-syntax) without `ufrag` attribute) and rejecting it.
- The `session-terminate` reason was a bit unexpected.

#### Expected result

I would have expected some vague "message was bogus", e.g.:

```xml
<iq type="set"><jingle sid="sid" action="session-terminate" xmlns="urn:xmpp:jingle:1"><reason><failed-application/><text>transport missing required ufrag attribute</text></reason></jingle></iq>
```

#### Actual result

```xml
<iq type="set"><jingle sid="sid" action="session-terminate" xmlns="urn:xmpp:jingle:1"><reason><failed-application/><text>Attempt to invoke interface method &apos;int java.lang.CharSequence.length()&apos; on a null object reference</text></reason></jingle></iq>
```

#### Debug output

```
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at com.google.common.base.CharMatcher.indexIn(CharMatcher.java:560)
        at com.google.common.base.CharMatcher.indexIn(CharMatcher.java:541)
        at com.google.common.base.CharMatcher.matchesNoneOf(CharMatcher.java:527)
        at com.google.common.base.CharMatcher.matchesAnyOf(CharMatcher.java:493)
        at eu.siacs.conversations.xmpp.jingle.SessionDescription.checkNoWhitespace(SessionDescription.java:276)
        at eu.siacs.conversations.xmpp.jingle.SessionDescription.of(SessionDescription.java:149)
        at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.receiveSessionAccept(JingleRtpConnection.java:384)
        at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.receiveSessionAccept(JingleRtpConnection.java:373)
        at eu.siacs.conversations.xmpp.jingle.JingleRtpConnection.deliverPacket(JingleRtpConnection.java:181)
        at eu.siacs.conversations.xmpp.jingle.JingleConnectionManager.deliverPacket(JingleConnectionManager.java:86)
        at eu.siacs.conversations.services.XmppConnectionService.lambda$createConnection$11(XmppConnectionService.java:1403)
        at eu.siacs.conversations.services.XmppConnectionService.lambda$createConnection$11$XmppConnectionService(Unknown Source:0)
        at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$hpm3lnS9Aw2KA3PtqFceFnMuR-o.onJinglePacketReceived(Unknown Source:2)
        at eu.siacs.conversations.xmpp.XmppConnection.processIq(XmppConnection.java:737)
        at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:642)
        at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:490)
        at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:810)
        at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:474)
        at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:382)
        at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:461)
        at java.lang.Thread.run(Thread.java:764)
```

If I understand correctly, this function expects `input != null`:

https://github.com/iNPUTmice/Conversations/blob/00bc7a4b0621c06d066d83f8763d344039d05d1c/src/main/java/eu/siacs/conversations/xmpp/jingle/SessionDescription.java#L275-L280

However, it looks like it is called with `input == null` (since the attribute is absent) here:

https://github.com/iNPUTmice/Conversations/blob/00bc7a4b0621c06d066d83f8763d344039d05d1c/src/main/java/eu/siacs/conversations/xmpp/jingle/SessionDescription.java#L144-L149

It might make sense to null-check `input`s for `checkNoWhitespace`, to increase Conversations robustness.

---
Thanks for this awesome piece of software.

**Comment by rhymecat** [comment]
Indeed, a duplicate, sorry about that.
I agree with the response in the other issue.
Still, it might make sense to reword the error message to something generic.
(Not closing, in case you agree.)
