### ISSUE TITLE
HTTP file upload not working with .onion addresses

### ISSUE THREAD

**Issue by e12005490** [iNPUTmice/Conversations#4039]
#### General information

* **Version:** 2.9.7
* **Device:** Samsung Galaxy S6
* **Android Version:**  /e/ 0.7 (based on android 7.1.2)
* **Server name:** self hosted (.onion)
* **Server software:** ejabberd 21.01-2
* **Installed server modules:** All XEPs appearing in the server info except for External Service Discovery and MAM
* **Conversations source:** F-Droid

#### Steps to reproduce

Trying to send a file with HTTP file upload enabled on a .onion ejabberd server.

#### Expected result

What is the expected output? 
The file should be sent.

#### Actual result

What do you see instead?
`delivery failed` with error message "Unable to resolve host <...>: No address associated with hostname".

I believe this is related to #3894 and similar issues, which conclude it is server-related. I thought this was weird, because the error in the log (exception posted below) and in the app suggest this is a DNS resolution problem.

The exception is thrown at HttpUploadConnection.java:189, which is a call to HttpURLConnection.connect(). I searched for related problems, and I found [this StackOverflow post](https://stackoverflow.com/questions/44369862/java-socks-proxy-uses-local-dns) saying that apparently it might be a bug with `URLConnection`s not correctly resolving addresses through a SOCKS proxy. I think this is possible, because my ejabberd server correctly receives the slot request sent by the client:

````
2021-03-18 11:49:42.087565+01:00 [info] <0.438.0>@mod_http_upload:create_slot/7:832 Got HTTP upload slot for admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion/Conversations.jtPa (file: cR9BDaBAR5aIJGUVIzeuzQ.jpg, size: 97621)
````

and (as far as I can understand from SlotRequester.java) the slot request does not use the same connection as the file upload.

Maybe I'm wrong, but if not, I hope this is helpful, and I'd be happy to provide more information if needed.

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Conversations and include all the
steps it takes to reproduce the problem.

````
$ adb logcat -s conversations
--------- beginning of system
--------- beginning of main
03-18 11:48:33.754 19846 19846 D conversations: action: null
03-18 11:48:33.813 19846 19846 D conversations: ConversationsOverviewFragment.onStart()
03-18 11:48:33.816 19846 19846 D conversations: ConversationsOverviewFragment.onResume()
03-18 11:48:34.007 19846 19846 D conversations: ForegroundService: off
03-18 11:48:34.116 19846 19846 D conversations: initializing database...
03-18 11:48:34.116 19846 19846 D conversations: restoring accounts...
03-18 11:48:34.127 19846 19846 D conversations: restoring conversations...
03-18 11:48:34.129 19846 19846 D conversations: finished restoring conversations in 2ms
03-18 11:48:34.130 19846 19879 D conversations: restoring roster...
03-18 11:48:34.133 19846 19846 D conversations: starting file observer
03-18 11:48:34.156 19846 19879 D conversations: restoring messages...
03-18 11:48:34.160 19846 19846 D conversations: ForegroundService: on
03-18 11:48:34.161 19846 19846 D conversations: update unread count to 0
03-18 11:48:34.190 19846 19879 D conversations: finished restoring messages in 34ms
03-18 11:48:34.201 19846 19846 D conversations: ForegroundService: on
03-18 11:48:34.239 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: connecting
03-18 11:48:34.240 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: connect to ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion via Tor. directTls=false
03-18 11:48:34.366 19846 19846 D conversations: resetting all attempt counts
03-18 11:48:34.388 19846 19846 D conversations: app switched into foreground
03-18 11:48:34.411 19846 19880 D conversations: found 0 changed files on start up. total=15. (31ms)
03-18 11:48:34.570 19846 19882 D conversations: start merging phone contacts with roster
03-18 11:48:34.570 19846 19882 D conversations: finished merging phone contacts
03-18 11:48:34.747 19846 19907 D conversations: updated dynamic shortcuts
03-18 11:48:37.035 19846 19846 D conversations: ConversationsOverviewFragment.onPause()
03-18 11:48:37.770 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion/Conversations.jtPa: Authenticating with SCRAM-SHA-1
03-18 11:48:38.869 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: logged in
03-18 11:48:39.265 19846 19846 D conversations: extras Bundle[{jid=admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, init=false}]
03-18 11:48:39.265 19846 19846 D conversations: force register=null
03-18 11:48:40.719 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: not counting stanza(IqPacket). Not in smacks session.
03-18 11:48:40.723 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: starting service discovery
03-18 11:48:40.746 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: server caps came from cache
03-18 11:48:41.124 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: stream management(3) enabled (resumable)
03-18 11:48:41.516 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: Requesting block list
03-18 11:48:42.177 19846 19897 D conversations: Received blocklist update from server
03-18 11:48:42.382 19846 19897 D conversations: AxolotlService (admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion): Bundle 802008666 in PEP was current
03-18 11:48:42.382 19846 19897 D conversations: AxolotlService (admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion): Announcing device 802008666
03-18 11:48:42.383 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: successfully enabled carbons
03-18 11:48:42.385 19846 19897 D conversations: {running nodes/ejabberd@localhost/shutdown=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#set-motd-allhosts=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, running nodes/ejabberd@localhost/backup/backup=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#edit-motd-allhosts=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, running nodes/ejabberd@localhost/import/dir=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#announce=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, ping=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#announce-all=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, running nodes/ejabberd@localhost/restart=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#get-user-password=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, running nodes/ejabberd@localhost/import/file=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#change-user-password=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#get-online-users-num=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, running nodes/ejabberd@localhost/DB=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#set-motd=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#delete-motd=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#edit-motd=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#end-user-session=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#get-registered-users-num=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, running nodes/ejabberd@localhost/backup/textfile=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#announce-allhosts=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#user-stats=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#add-user=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#delete-motd-allhosts=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#get-user-lastlogin=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#announce-all-allhosts=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, http://jabber.org/protocol/admin#delete-user=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, running nodes/ejabberd@localhost/backup/restore=ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion}
03-18 11:48:42.392 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: online with resource Conversations.jtPa
03-18 11:48:42.405 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: fetching roster version 1620af093cc73ed848954d52f0cf74f22e0ed2a5
03-18 11:48:42.406 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion sending csi//active
03-18 11:48:42.878 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: retrieved own device list: [802008666]
03-18 11:48:43.104 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: 0 bookmarks have been removed
03-18 11:48:43.104 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: processing bookmark PEP event
03-18 11:48:43.169 19846 19897 D conversations: AxolotlService (admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion): Received PEP device list [802008666] update from admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, processing... 
03-18 11:48:43.169 19846 19897 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: ignoring duplicate own device id list
03-18 11:48:43.200 19846 19915 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: persisted roster in 22ms
03-18 11:48:43.226 19846 19915 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: persisted roster in 19ms
03-18 11:48:43.232 19846 19897 D conversations: AxolotlService (admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion): Received PEP device list [582204034] update from hilbert@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, processing... 
03-18 11:48:43.261 19846 19915 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: persisted roster in 20ms
03-18 11:48:43.942 19846 19846 D conversations: extras Bundle[{jid=admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion, init=false}]
03-18 11:48:43.942 19846 19846 D conversations: force register=null
03-18 11:48:49.001 19846 19846 D conversations: ConversationsOverviewFragment.onStart()
03-18 11:48:49.002 19846 19846 D conversations: ConversationsOverviewFragment.onResume()
03-18 11:49:14.065 19846 19846 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion send ping (action=eu.siacs.conversations.POST_CONNECTIVITY_CHANGE,lowTimeout=false)
03-18 11:49:32.971 19846 19846 D conversations: ConversationFragment.onAttach()
03-18 11:49:32.972 19846 19846 D conversations: ConversationsOverviewFragment.onPause()
03-18 11:49:32.972 19846 19846 D conversations: ConversationsOverviewFragment.onDestroyView()
03-18 11:49:33.012 19846 19846 D conversations: reInit(hasExtras=true)
03-18 11:49:33.012 19846 19846 D conversations: trimming conversation
03-18 11:49:33.041 19846 19846 D conversations: scrolledToBottomAndNoPending=true
03-18 11:49:33.041 19846 19846 D conversations: jump to first unread message
03-18 11:49:40.366 19846 19846 D conversations: send file message
03-18 11:49:40.369 19846 19846 D conversations: using 12-byte IV for file transmission
03-18 11:49:41.191 19846 19929 D conversations: uploading to http://ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion:5443/upload/58f30486cdfd7d490b06ef9dd37519856e360fd7/H1ElG81Ls1IIR95RkHdQ3kzui2r3y8PmRDgtd3jW/cR9BDaBAR5aIJGUVIzeuzQ.jpg w/ read timeout of 62s
**03-18 11:49:41.254 19846 19929 D conversations: http upload failed Unable to resolve host "ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion": No address associated with hostname**
03-18 11:49:41.270 19846 19929 D conversations: admin@ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion: suppressing failed delivery notification because conversation is open
03-18 11:49:42.511 19846 19846 D conversations: ConversationFragment.onDestroyView()
03-18 11:49:42.526 19846 19846 D conversations: ConversationsOverviewFragment.onStart()
03-18 11:49:42.526 19846 19846 D conversations: ConversationsOverviewFragment.onResume()
````

#### Exception

````
03-18 11:49:41.246 19846 19929 W System.err: java.net.UnknownHostException: Unable to resolve host "ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion": No address associated with hostname
03-18 11:49:41.251 19846 19929 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
03-18 11:49:41.251 19846 19929 W System.err: 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
03-18 11:49:41.252 19846 19929 W System.err: 	at java.net.InetAddress.getAllByName(InetAddress.java:752)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:346)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
03-18 11:49:41.252 19846 19929 W System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
**03-18 11:49:41.252 19846 19929 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection.upload(HttpUploadConnection.java:189)**
03-18 11:49:41.253 19846 19929 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection.access$300(HttpUploadConnection.java:32)
03-18 11:49:41.253 19846 19929 W System.err: 	at eu.siacs.conversations.http.HttpUploadConnection$1.lambda$success$0(HttpUploadConnection.java:141)
03-18 11:49:41.253 19846 19929 W System.err: 	at eu.siacs.conversations.http.-$$Lambda$HttpUploadConnection$1$ektaHXFqxgW3UQRYD5-n6pWZA0w.run(lambda)
03-18 11:49:41.253 19846 19929 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-18 11:49:41.253 19846 19929 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-18 11:49:41.253 19846 19929 W System.err: 	at java.lang.Thread.run(Thread.java:761)
03-18 11:49:41.253 19846 19929 W System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
03-18 11:49:41.254 19846 19929 W System.err: 	at libcore.io.Posix.android_getaddrinfo(Native Method)
03-18 11:49:41.254 19846 19929 W System.err: 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
03-18 11:49:41.254 19846 19929 W System.err: 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
03-18 11:49:41.254 19846 19929 W System.err: 	... 18 more
03-18 11:49:41.254 19846 19929 D conversations: http upload failed Unable to resolve host "ofyms4nrvwscwn75edbllsbmqbvjz3s3kyxd7d7mjwswfgkrkoafvoad.onion": No address associated with hostname
````

**Comment by iNPUTmice** [comment]
> I searched for related problems, and I found this StackOverflow post saying that apparently it might be a bug with URLConnections not correctly resolving addresses through a SOCKS proxy. 

seems plausible to me.

**Comment by ValHeimer** [comment]
Also tested with Conversations 2.9.9, works too

**Comment by ValHeimer** [comment]
Indeed, I make some tests:
- Android 10: works fine with Conversations 2.9.6 and 2.9.9
- Android 5.1: does not work with Conversations 2.9.6, but woks with 2.9.9

**Comment by e12005490** [comment]
I just tried using file upload with Conversations 2.9.9, and it nows works perfectly. I haven't modified my ejabberd.yml in the meantime, so I think it wasn't server related? @ValHeimer

I thought it might have something to do with my /e/ ROM, but some friends of mine with a stock android ROM were having the same issue up until 2.9.9.

I'm closing the issue since the problem seems to be resolved.
