### ISSUE TITLE
Restore of backup not working

### ISSUE THREAD

**Issue by sjaeckel** [iNPUTmice/Conversations#4096]
Both versions: 2.9.13+fcr

Steps to reproduce:
1. On device 1 - "Create backup"
2. Transfer ceb files from device 1 to device 2
3. On device 2 - "Restore backup"
4. Navigate to the ceb file and select it

Expected behavior:
Backup is restored

Actual result:
Message is displayed "The file you selected is not a Conversations backup file"

Side-note:
This also happens when trying to restore the ceb file on the device where the backup was created.

**Comment by sjaeckel** [comment]
Looks like there went something wrong while transferring the file. If I use the original file on the device where the backup is created, it seems to work.

**Comment by sjaeckel** [comment]
I've reopened this issue as I'm not sure where the problem lies and I'd like to have your opinion on it.

I've created the backup and transferred the file via the NextCloud client to the new device.

After downloading in the NextCloud client I selected the ceb file from the "Open from" dialog via "Nextcloud", navigating to the file, selecting it and this resulted in the aforementioned error.

When I navigated to the file via the full path `Android/media/com.nextcloud.client/nextcloud/<account>/path/to/file.ceb` and retried it worked as expected.

**Comment by licaon-kter** [comment]
Put the file in /Conversations/Backup
Does it always work?

**Comment by iNPUTmice** [comment]
Do you have a log?

**Comment by sjaeckel** [comment]
How can I get one?

**Comment by iNPUTmice** [comment]
https://github.com/iNPUTmice/Conversations/blob/master/README.md#how-do-i-debug-conversations

**Comment by sjaeckel** [comment]
The only thing that is printed on failure in the log is

```
directory not found: /storage/emulated/0/Quicksy/Backup
directory not found: /storage/emulated/0/Conversations/Backup
```

**Comment by licaon-kter** [comment]
@sjaeckel did you allow storage permission when asked?

**Comment by sjaeckel** [comment]
Yes, Storage permission is set to "Allow".

I've also tried to add an attachment to a message via the same logic and that worked.

**Comment by iNPUTmice** [comment]
My best guess is that the NextCloud client doesn’t grant us permission to access that file. However 98ffadd87d8a6118af39fb00b2cb02d075e37951 will log the full stack trace.

**Comment by ValdikSS** [comment]
@iNPUTmice, in my case backup is not restored with sqlite unique index error:

```
01-24 14:31:32.650 23575 23640 D conversations: error restoring backup content://com.android.providers.downloads.documents/document/34
01-24 14:31:32.650 23575 23640 D conversations: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: messages.uuid (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:832)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1824)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1751)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService.importBackup(ImportBackupService.java:260)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService.lambda$onStartCommand$0(ImportBackupService.java:108)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService.$r8$lambda$_Gblybgouv1Yt7P2F13nA3J9Xfw(Unknown Source:0)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService$$ExternalSyntheticLambda0.run(Unknown Source:6)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
01-24 14:31:32.650 23575 23640 D conversations:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-24 14:31:32.650 23575 23640 D conversations:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-24 14:31:32.650 23575 23640 D conversations:         at java.lang.Thread.run(Thread.java:919)
```

The backup was created with 2.10.2+pcr, and I'm trying to restore to the same version.

**Comment by hermann-san** [comment]
@iNPUTmice  in the [FAQ](https://github.com/iNPUTmice/Conversations) it is described how to do the backup, but I could not see how to do the restore. I.E.  tap on the ceb file and open with Conversations. Or have I overlooked it?
For me it was not obvious how to restore the backup. Only when I've read above to tap on the file, it was clear to me.

**Comment by licaon-kter** [comment]
@hermann-san

Install Conversations, try to open a .ceb file via a File manager?

Start a fresh install of Conversations, upper right menu, Restore?

A running Conversations, accounts, upper right menu, Restore?

Which one did you try?

**Comment by hermann-san** [comment]
@licaon-kter  Thanks, I already got it working, but I thought that the FAQ could be improved.
