### ISSUE TITLE
Image is not compressed before sending

### ISSUE THREAD

**Issue by Andy-2639** [iNPUTmice/Conversations#4125]
Steps to reproduce:
* Take image with the camera app (org.lineageos.snap version 2.02.072 (8ad7c868bd-00))
* Image is stored on SD card, 11 MiB
* View image in gallery (com.android.gallery3d version 1.1.40030), share it via share button with Conversations contact (with myself, as I'm logged in via a second device)
* Full 11 MiB image is sent via HTTP upload instead of a compressed image. In Conversations, Image Compression is set to "Large images only"
* When I send the image from Conversation with "Choose picture", it gets compressed before sending it.

Expected result: image is compressed before sending it.

Phone: Sony Xperia XA2 (H4113)
Android: 11 (LineageOS 18.1-20210708-NIGHTLY-pioneer)
Conversations: 2.9.13+fcr from F-Droid

**Comment by licaon-kter** [comment]
Seeing the same sometimes.

@Andy-2639 
> When I send the image from Conversation with "Choose picture", it gets compressed before sending it.

But WHERE do you choose this picture from? Document app or Document app->Gallery->Image? Can you test if different?

IIRC, it depends on the (gallery or whatever) app if the file that Conversations receives is (presented as) an image or as a (unspecified) file. So if Conversations receives it as a file it doesn't try to compress it.

**Comment by Andy-2639** [comment]
@licaon-kter
> But WHERE do you choose this picture from? Document app or Document app->Gallery->Image? Can you test if different?

I don't understand your question. What do you mean with "Document app"?

1. I open my gallery app (com.android.gallery3d)
2. In the timeline, I choose a picture and use the share button in the top right corner. 
![6d671g3qbwzfxdtx](https://user-images.githubusercontent.com/13392804/129488260-35acb550-28f1-43f7-88bd-113862022ebe.png)
3. In the input field of Conversations, the image preview (before sending) is gray instead of showing a thumbnail of the image. This is not masked by me - I just masked my name in the top. 
![vln2v8sw8v5l6n6j](https://user-images.githubusercontent.com/13392804/129488291-0c47c653-e8aa-41ae-9826-ef2e9e8871f5.png)
4. Conversations sends the image uncompressed and I get a 0-byte file `/storage/emulated/0/Conversations/Media/Conversations Images/33ec0220-6ecf-4972-ad35-b86c19d281de.jpg`

Logcat:
```
08-15 20:06:42.831 D/conversations( 4198): toggle forced foreground service after receiving event (action=contact_chooser)
08-15 20:06:42.844 D/conversations( 4198): ForegroundService: on
08-15 20:06:44.751 D/conversations( 4198): action: android.intent.action.SEND
08-15 20:06:44.791 D/conversations( 4198): ConversationsOverviewFragment.onStart()
08-15 20:06:44.793 D/conversations( 4198): ConversationsOverviewFragment.onResume()
08-15 20:06:44.831 D/conversations( 4198): ***@*** send ping (action=ui,lowTimeout=false)
08-15 20:06:44.835 D/conversations( 4198): app switched into foreground
08-15 20:06:44.848 D/conversations( 4198): ConversationFragment.onAttach()
08-15 20:06:44.865 D/conversations( 4198): reInit(hasExtras=true)
08-15 20:06:44.865 D/conversations( 4198): trimming conversation
08-15 20:06:44.867 D/conversations( 4198): scrolledToBottomAndNoPending=true
08-15 20:06:44.867 D/conversations( 4198): jump to first unread message
08-15 20:06:44.873 D/conversations( 4198): ConversationsOverviewFragment.onPause()
08-15 20:06:44.873 D/conversations( 4198): ConversationsOverviewFragment.onDestroyView()
08-15 20:06:44.902 D/conversations( 4198): ***@*** received pubsub notification for node=eu.siacs.conversations.axolotl.bundles:***
08-15 20:06:44.944 D/conversations( 4198): ***@***: persisted roster in 25ms
08-15 20:06:52.228 D/conversations( 4198): AxolotlService (***@***): Finding devices without session for ***@***
08-15 20:06:52.229 D/conversations( 4198): ConversationsActivity.commitAttachments() - attaching image to conversations. CHOOSE_IMAGE
08-15 20:06:52.302 D/conversations( 4198): attachImage: type=1
08-15 20:06:52.305 D/conversations( 4198): copy image (content://media/external/images/media/3801) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/33ec0220-6ecf-4972-ad35-b86c19d281de.jpg
08-15 20:06:52.328 D/conversations( 4198): received uri permission for content://media/external/images/media/3801
08-15 20:06:52.362 D/conversations( 4198): reading bitmap with sample size 1
08-15 20:06:52.366 D/conversations( 4198): unable to compress image. fall back to file transfer
08-15 20:06:52.366 D/conversations( 4198): eu.siacs.conversations.persistance.FileBackend$ImageCompressionException: Source file was not an image
08-15 20:06:52.366 D/conversations( 4198):      at eu.siacs.conversations.persistance.FileBackend.copyImageToPrivateStorage(FileBackend.java:732)
08-15 20:06:52.366 D/conversations( 4198):      at eu.siacs.conversations.persistance.FileBackend.copyImageToPrivateStorage(FileBackend.java:777)
08-15 20:06:52.366 D/conversations( 4198):      at eu.siacs.conversations.persistance.FileBackend.copyImageToPrivateStorage(FileBackend.java:792)
08-15 20:06:52.366 D/conversations( 4198):      at eu.siacs.conversations.services.XmppConnectionService.lambda$attachImageToConversation$2(XmppConnectionService.java:598)
08-15 20:06:52.366 D/conversations( 4198):      at eu.siacs.conversations.services.XmppConnectionService.lambda$attachImageToConversation$2$XmppConnectionService(Unknown Source:0)
08-15 20:06:52.366 D/conversations( 4198):      at eu.siacs.conversations.services.-$$Lambda$XmppConnectionService$8tVnRBWKkP6lTLOFlG4QG_r3SVk.run(Unknown Source:12)
08-15 20:06:52.366 D/conversations( 4198):      at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
08-15 20:06:52.366 D/conversations( 4198):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-15 20:06:52.366 D/conversations( 4198):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-15 20:06:52.366 D/conversations( 4198):      at java.lang.Thread.run(Thread.java:923)
08-15 20:06:52.367 D/conversations( 4198): attachFile: type=2
08-15 20:06:52.367 D/conversations( 4198): counterpart=null
08-15 20:06:52.367 D/conversations( 4198): guessMimeTypeFromUriAndMime content://media/external/images/media/3801 and mime=image/jpeg
08-15 20:06:52.411 D/conversations( 4198): send file message
08-15 20:06:52.412 D/conversations( 4198): using 12-byte IV for file transmission
08-15 20:06:52.490 D/conversations( 4198): uploading file to https://upload.***/upload/***/***/IMG_20210815_200628.jpg?v=***
08-15 20:07:00.848 D/conversations( 4198): toggle forced foreground service after receiving event (action=ping)
08-15 20:07:00.861 D/conversations( 4198): ForegroundService: on
08-15 20:07:22.881 D/conversations( 4198): finished uploading file
08-15 20:07:22.893 D/conversations( 4198): AxolotlService (***@***): Cache miss: b8fc0c38-1354-4079-8d95-d4feadf0af01
08-15 20:07:22.921 D/conversations( 4198): AxolotlService (***@***): Generated message, caching: b8fc0c38-1354-4079-8d95-d4feadf0af01
08-15 20:07:22.922 D/conversations( 4198): AxolotlService (***@***): Cache hit: b8fc0c38-1354-4079-8d95-d4feadf0af01
08-15 20:07:22.943 D/conversations( 4198): media scanner scanned wrong file
08-15 20:07:33.946 D/conversations( 4198): ConversationsOverviewFragment.onStart()
08-15 20:07:33.947 D/conversations( 4198): ConversationsOverviewFragment.onResume()
08-15 20:07:33.948 D/conversations( 4198): ConversationFragment.onDestroyView()
08-15 20:07:34.294 D/conversations( 4198): ConversationsOverviewFragment.onPause()
08-15 20:07:34.475 D/conversations( 4198): app switched into background
08-15 20:07:34.487 D/conversations( 4198): ConversationsOverviewFragment.onDestroyView()
08-15 20:07:34.488 D/conversations( 4198): ConversationsOverviewFragment.onDestroy()
```
I guess that Conversations cannot read/copy the image?

When I share a picture with my Files app (com.android.documentsui), it works.

**Comment by licaon-kter** [comment]
Try Simple Gallery Pro from F-Droid too.

Share from app to Conversations is one case. I meant in Convursations...press attach...image...choose image.

**Comment by dietergithub** [comment]
> Image is not compressed before sending
> Expected result: image is compressed before sending it.

Sounds like a duplicate of issue #3994

**Comment by Andy-2639** [comment]
With Simple Gallery Pro, I get the same effect as with com.android.gallery3d: the image is not compressed.
```
08-21 17:46:44.393 D/conversations( 4198): attachImage: type=1
08-21 17:46:44.397 D/conversations( 4198): copy image (content://media/external/images/media/3812) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/2bd26d52-4851-41db-8366-a809aacc24f6.jpg
08-21 17:46:44.404 D/conversations( 4198): received uri permission for content://media/external/images/media/3812
08-21 17:46:44.473 D/conversations( 4198): reading bitmap with sample size 1
08-21 17:46:44.489 D/conversations( 4198): unable to compress image. fall back to file transfer
08-21 17:46:44.489 D/conversations( 4198): eu.siacs.conversations.persistance.FileBackend$ImageCompressionException: Source file was not an image
```

> Conversations...press attach...image...choose image

Today, it worked with compressing the image - the same as when sharing with com.android.documentsui.
```
08-21 17:48:01.866 D/conversations( 4198): attachImage: type=1
08-21 17:48:01.869 D/conversations( 4198): copy image (content://com.android.externalstorage.documents/document/956F-397F%3ADCIM%2FCamera%2FIMG_20210821_174614.jpg) to private storage /storage/emulated/0/Conversations/Media/Conversations Images/af9ed1d9-503b-433a-b2d2-186ed1563dd6.jpg
08-21 17:48:01.890 D/conversations( 4198): received uri permission for content://com.android.externalstorage.documents/document/956F-397F%3ADCIM%2FCamera%2FIMG_20210821_174614.jpg
08-21 17:48:01.921 D/conversations( 4198): reading bitmap with sample size 1
08-21 17:48:02.792 D/conversations( 4198): send file message
```
But I remember that it also didn't work with "Conversations...press attach...image...choose image" earlier.

In LineageOS 18.1/Android 11, I can choose from which app I select the picture after I chose to attach a picture from Conversations. The default app seems to be the Files app (com.android.documentsui) - which works. When I select choosing the image from the Gallery instead, it doesn't work as when starting from the gallery to send the image.

Maybe it has to with the file url Conversations gets?
* failure: `content://media/external/images/media/3812` vs.
* working: `content://com.android.externalstorage.documents/document/956F-397F%3ADCIM%2FCamera%2FIMG_20210821_174614.jpg`

**Comment by licaon-kter** [comment]
You realise it says there that "it could not compress the image" so it send the file, right?

Try with other images, bigger than 1920px ones

**Comment by Andy-2639** [comment]
I used the same image for the tests: 2608 x 4624 px - taken with the phones camera (picture size 16:9, 12.1 megapixels)
![IMG_20210821_174614](https://user-images.githubusercontent.com/13392804/130328966-ec9a01f4-245c-47e5-a1c8-9cc615497017.jpg)

**Comment by licaon-kter** [comment]
Ok, I can repro, rotate image 90 degrees, save, retry.

The code has some preferences on aspect ratios, that could be fixed.
