### ISSUE TITLE
Take Picture - No Application Found

### ISSUE THREAD

**Issue by mrjfilippo** [iNPUTmice/Conversations#4159]
I have the Redmi Note 7 Pro on PixelExperience ROM. When I try to take a picture through Conversations, it gives the error message "No application found". I use Google Camera and no other camera apps are installed and all permission have been set to allowed. Other apps who need access to the camera don't have this issue.

Thank you for your work, please let me know what other information is needed to better assist.

**Comment by licaon-kter** [comment]
Is Gcam set as default in Android Settings?

Can you get a logcat for the moment you try to use the camera?

Same error for "Record Video" in Conversations?

**Comment by mrjfilippo** [comment]
Yes I have the Gcam set as default. Just to make it, I did reset and when prompting the hardware camera shortcut, I set as default. The only other option was Tasker. I do get the same error if I want to record a video. 

I also just noticed I have Camera Go, but it says it is not install for this user. Could that interfere? It must have came with the ROM by default and I forced uninstalled it.

I tried to pinpoint the logcat moment, hopefully this is it. The first line is what comes up, then after that I can't really follow! Thanks for the quick reply.

09-09 13:29:45.263 21058 17433 D OpenGLRenderer: endAllActiveAnimators on 0x7e15737570 (MenuPopupWindow$MenuDropDownListView) with handle 0x7d355d1480
09-09 13:33:27.681  1401  3872 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10235; state: DISABLED
09-09 13:33:27.681  1401  3872 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10235; state: DISABLED
09-09 13:33:27.681  1401  1530 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10235; state: DISABLED
09-09 13:33:27.698   771   771 D Zygote  : Forked child process 3797
09-09 13:33:27.700  1401  1530 I ActivityManager: Start proc 3797:com.xiaomi.smarthome:pushservice/u0a235 for service {com.xiaomi.smarthome/com.xiaomi.push.service.XMPushService}
09-09 13:33:27.706  3797  3797 I libc    : SetHeapTaggingLevel: tag level set to 0
09-09 13:33:27.716  3797  3797 E ome:pushservic: Not starting debugger since process cannot load the jdwp agent.
09-09 13:33:27.732  1401  3872 W ActivityManager: Background start not allowed: service Intent { cmp=com.xiaomi.smarthome/com.xiaomi.mipush.sdk.PushMessageHandler } to com.xiaomi.smarthome/com.xiaomi.mipush.sdk.PushMessageHandler from pid=3139 uid=10235 pkg=com.xiaomi.smarthome startFg?=false
09-09 13:33:27.753  3797  3797 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
09-09 13:33:27.758  1401  3872 W ActivityManager: Background start not allowed: service Intent { cmp=com.xiaomi.smarthome/com.xiaomi.mipush.sdk.MessageHandleService } to com.xiaomi.smarthome/com.xiaomi.mipush.sdk.MessageHandleService from pid=3139 uid=10235 pkg=com.xiaomi.smarthome startFg?=false
09-09 13:33:27.766  3139  3830 E mcssdk---: MCS-->isExistPackage NameNotFoundException:com.coloros.mcs
09-09 13:33:27.767  3139  3830 E mcssdk---: MCS-->isExistPackage NameNotFoundException:com.coloros.mcs
09-09 13:33:27.768  3797  3797 I ome:pushservic: The ClassLoaderContext is a special shared library.
09-09 13:33:27.821  3797  3797 W ome:pushservic: JIT profile information will not be recorded: profile file does not exist.
09-09 13:33:27.855  3797  3797 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
09-09 13:33:27.856  3797  3797 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
09-09 13:33:27.864  3797  3797 I MultiDex: VM with version 2.1.0 has multidex support
09-09 13:33:27.865  3797  3797 I MultiDex: Installing application
09-09 13:33:27.865  3797  3797 I MultiDex: VM has multidex support, MultiDex support library is disabled.
09-09 13:33:27.885  3797  3797 I MMKV    : <native-bridge.cpp:101::JNI_OnLoad> current API level = 30
09-09 13:33:27.885  3797  3797 I MMKV    : <MMKV.cpp:154::initialize> version v1.2.2 page size:4096
09-09 13:33:27.886  3797  3797 I MMKV    : <MMKV.cpp:165::initialize> armv8 AES instructions is supported
09-09 13:33:27.886  3797  3797 I MMKV    : <MMKV.cpp:171::initialize> armv8 CRC32 instructions is supported
09-09 13:33:27.886  3797  3797 I MMKV    : <MMKV.cpp:192::initializeMMKV> root dir: /data/user/0/com.xiaomi.smarthome/files/mmkv
09-09 13:33:27.901  3797  3797 W WMRouter: !!当前未设置Logger,建议通过 Debugger.setLogger()方法设置Logger
09-09 13:33:27.901  3797  3797 W WMRouter: !!并在测试环境通过 Debugger.EnableLog(true)方法开启日志
09-09 13:33:27.901  3797  3797 W WMRouter: !!通过Debugger.setEnableDebug(true)方法在测试环境及时抛出严重类型异常
09-09 13:33:27.920  1401  3834 W NotificationService: Toast already killed. pkg=eu.siacs.conversations token=android.os.BinderProxy@8eb02a6
09-09 13:33:27.964  1401  3834 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.xiaomi.smarthome:getSerial:-1
09-09 13:33:27.997  3797  3797 I TetheringManager: registerTetheringEventCallback:com.xiaomi.smarthome
09-09 13:33:28.034  1401  3834 I ActivityManager: Killing 28795:android.process.media/u0a62 (adj 985): empty #17
09-09 13:33:28.053  3797  3847 V XMPush-3797: android.content.pm.PackageManager$NameNotFoundException: com.xiaomi.xmsf
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:206)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:178)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at com.xiaomi.push.g.O00000Oo(Unknown Source:6)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at com.xiaomi.push.service.n.a(Unknown Source:1000)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at com.xiaomi.push.service.n.a(Unknown Source:11)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at com.xiaomi.push.service.ab.a(Unknown Source:18)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at com.xiaomi.push.service.cl.a(Unknown Source:2)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at com.xiaomi.push.service.XMPushService$j.run(Unknown Source:20)
09-09 13:33:28.053  3797  3847 V XMPush-3797:   at com.xiaomi.push.service.j$c.run(Unknown Source:159)
09-09 13:33:28.054  3797  3847 E libc    : Access denied finding property "ro.vendor.oplus.regionmark"
09-09 13:33:28.061  3139  3162 E ProcessUtil: /prop
09-09 13:33:28.061  3139  3162 E ProcessUtil: java.io.FileNotFoundException: /proc/3797/cmdline: open failed: ENOENT (No such file or directory)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at libcore.io.IoBridge.open(IoBridge.java:492)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at java.io.FileInputStream.<init>(FileInputStream.java:160)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at java.io.FileInputStream.<init>(FileInputStream.java:115)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at _m_j.ftm.O000000o(SourceFile:66)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at _m_j.ftm.O000000o(SourceFile:44)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at com.xiaomi.smarthome.core.server.CoreApiStub$1.run(SourceFile:1094)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at android.os.Handler.handleCallback(Handler.java:938)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at android.os.Handler.dispatchMessage(Handler.java:99)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at android.os.Looper.loop(Looper.java:223)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at android.os.HandlerThread.run(HandlerThread.java:67)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at _m_j.gpq.run(SourceFile:46)
09-09 13:33:28.061  3139  3162 E ProcessUtil: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at libcore.io.Linux.open(Native Method)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7550)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   at libcore.io.IoBridge.open(IoBridge.java:478)
09-09 13:33:28.061  3139  3162 E ProcessUtil:   ... 10 more
09-09 13:33:28.067  3797  3863 W System.err: com.xiaomi.smarthome.frame.core.CoreApi$CoreNotReadyException: isCoreReady false
09-09 13:33:28.069  3797  3863 W System.err:    at com.xiaomi.smarthome.frame.core.CoreApi.O00000Oo(SourceFile:292)
09-09 13:33:28.069  3797  3863 W System.err:    at com.xiaomi.smarthome.frame.core.CoreApi.O0000ooO(SourceFile:2297)
09-09 13:33:28.069  3797  3863 W System.err:    at com.xiaomi.smarthome.frame.core.CoreApi$9.O000000o(SourceFile:5480)
09-09 13:33:28.069  3797  3863 W System.err:    at _m_j.gsy.O00000Oo(SourceFile:355)
09-09 13:33:28.069  3797  3863 W System.err:    at _m_j.gsy.O000000o(SourceFile:303)
09-09 13:33:28.070  3797  3863 W System.err:    at _m_j.gsy.O00000o0(SourceFile:279)
09-09 13:33:28.070  3797  3863 W System.err:    at _m_j.gsy$1.run(SourceFile:73)
09-09 13:33:28.070  3797  3863 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-09 13:33:28.070  3797  3863 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-09 13:33:28.070  3797  3863 W System.err:    at java.lang.Thread.run(Thread.java:923)
09-09 13:33:28.092   771   771 I Zygote  : Process 28795 exited due to signal 9 (Killed)
09-09 13:33:28.122  1401  1557 I libprocessgroup: Successfully killed process cgroup uid 10062 pid 28795 in 87ms
09-09 13:33:29.627  3275  3607 V ==== sensetime info ====: version: v5.10.5, commit id: e1bfa95, build time: 2018-11-01T11:08:42
09-09 13:33:29.673 14602 14763 I A       : #handleLocale  en-US
09-09 13:33:29.675 14602 14763 I A       : #handleLocale  en-CA
09-09 13:33:29.677 14602 14763 I A       : #handleLocale  en-US
09-09 13:33:29.745 14602 14763 I A       : available language pack of en-US is version 5011
09-09 13:33:29.745 14602 14763 I A       : available language pack of en-CA is version 501
09-09 13:33:29.866  1401  3872 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10062; state: DISABLED
09-09 13:33:29.866  1401  3872 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10062; state: ENABLED
09-09 13:33:29.867  1401  1530 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10062; state: ENABLED
09-09 13:33:29.888   771   771 D Zygote  : Forked child process 3877
09-09 13:33:29.890  1401  1530 I ActivityManager: Start proc 3877:android.process.media/u0a62 for content provider {com.android.providers.downloads/com.android.providers.downloads.DownloadProvider}
09-09 13:33:29.899  3877  3877 E d.process.medi: Not starting debugger since process cannot load the jdwp agent.
09-09 13:33:29.952  3877  3877 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-09 13:33:29.953  3877  3877 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-09 13:33:30.037  3275  3607 I AdrenoGLES-0: QUALCOMM build                   : ab8b468, I1017670a82
09-09 13:33:30.037  3275  3607 I AdrenoGLES-0: Build Date                       : 02/05/21
09-09 13:33:30.037  3275  3607 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.07
09-09 13:33:30.037  3275  3607 I AdrenoGLES-0: Local Branch                     : mybrancheb67b55a-6fa6-f12c-ba74-1458d0b52af0
09-09 13:33:30.037  3275  3607 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
09-09 13:33:30.037  3275  3607 I AdrenoGLES-0: Remote Branch                    : NONE
09-09 13:33:30.037  3275  3607 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
09-09 13:33:30.038  3275  3607 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
09-09 13:33:30.038  3275  3607 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
09-09 13:33:30.086  3275  3607 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
09-09 13:33:30.105  3877  3911 V DownloadManager: Deleting /storage/emulated/0/Android/data/com.google.android.googlequicksearchbox/files/download_cache/soda-en-US-v5011.zip via provider delete
09-09 13:33:30.211 32484  2342 D awcn.DefaultHeartbeatImpl: |[seq:24752834.AWCN1_1] heartbeat session:Session@[24752834.AWCN1_1|http2_0rtt_open]
09-09 13:33:30.212 32484  2342 D awcn.TnetSpdySession: |[seq:24752834.AWCN1_1] ping host:https://acs4public.m.taobao.com thread:AWCN Scheduler1
09-09 13:33:30.217 32484  2342 D awcn.TnetSpdySession: |[seq:24752834.AWCN1_1] https://acs4public.m.taobao.com submit ping ms:45066 force:true
09-09 13:33:30.443  1401  1529 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10118; state: DISABLED
09-09 13:33:30.443  1401  1529 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10118; state: DISABLED
09-09 13:33:30.444  1401  1530 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10118; state: DISABLED
09-09 13:33:30.467   771   771 D Zygote  : Forked child process 3941
09-09 13:33:30.468  1401  1530 I ActivityManager: Start proc 3941:com.google.android.apps.turbo/u0a118 for broadcast {com.google.android.apps.turbo/com.google.android.apps.turbo.deadline.library.DeadlineUpdateReceiver}
09-09 13:33:30.472  3941  3941 I libc    : SetHeapTaggingLevel: tag level set to 0
09-09 13:33:30.479  3941  3941 E roid.apps.turb: Not starting debugger since process cannot load the jdwp agent.
09-09 13:33:30.504  3941  3941 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
09-09 13:33:30.507  3941  3941 I roid.apps.turb: The ClassLoaderContext is a special shared library.
09-09 13:33:30.604  3791 13419 I MediaProvider: Scanned external_primary due to REASON_DEMAND, found 0 items in 399ms, 0 inserts 0 updates 0 deletes
09-09 13:33:30.671 32484  2579 I awcn.TnetSpdySession: |[seq:24752834.AWCN1_1] ping receive Host:https://acs4public.m.taobao.com id:1
09-09 13:33:30.680  3941  3941 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-09 13:33:30.792  1401  2005 W ActivityManager: Unable to start service Intent { cmp=com.google.android.turboadapter/.GoogleBatteryService } U=0: not found
09-09 13:33:30.811  3941  3941 E ActivityThread: Service com.google.android.apps.turbo.deadline.library.DeadlineUpdateJobService has leaked ServiceConnection wg@de319c6 that was originally bound here
09-09 13:33:30.811  3941  3941 E ActivityThread: android.app.ServiceConnectionLeaked: Service com.google.android.apps.turbo.deadline.library.DeadlineUpdateJobService has leaked ServiceConnection wg@de319c6 that was originally bound here
09-09 13:33:30.811  3941  3941 E ActivityThread:        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1835)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1707)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1686)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1819)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at android.app.ContextImpl.bindService(ContextImpl.java:1749)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at android.content.ContextWrapper.bindService(ContextWrapper.java:756)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at wc.a(Unknown Source:4)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at vj.d(PG:4)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at com.google.android.apps.turbo.deadline.library.DeadlineUpdateJobService.c(PG:1)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at we.run(Unknown Source:2)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-09 13:33:30.811  3941  3941 E ActivityThread:        at java.lang.Thread.run(Thread.java:923)
09-09 13:33:30.811  1401  2005 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@48b4aa8
09-09 13:33:30.681  3941  3941 D NetworkSecurityConfig: No Network Security Config specified, using platform default
09-09 13:33:30.861 32276 32276 E oisc    : [com.icbc]AlarmJobService onStartJob
09-09 13:33:30.871 32276 32276 I oisc    : [com.icbc]AlarmJobService msg.what:999
09-09 13:33:30.872 32276 32276 I oisc    : [com.icbc]AlarmJobService定时已到，开始保活
09-09 13:33:30.879  2650  2678 I oiscSDK : [com.icbc]当前Userid:1001239159224
09-09 13:33:30.880  2650  2678 I oiscSDK : [com.icbc]开始保活
09-09 13:33:30.882 32276 32276 E oisc    : [com.icbc]AlarmJobService jobFinished
09-09 13:33:30.883 32276 32276 E oisc    : [com.icbc]JobSchedulerManager createAlarmJobInfo2start
09-09 13:33:30.883 32276 32276 E oisc    : [com.icbc]JobSchedulerManager createAlarmJobInfo
09-09 13:33:30.887 32276 32276 E oisc    : [com.icbc]JobSchedulerManager jobScheduler success
09-09 13:33:31.348  3941  3987 E SQLiteDatabase: Error inserting timezone=Asia/Shanghai timestamp_millis=1631165563000 battery_level=100 battery_saver=2 charge_type=2 place_key=null
09-09 13:33:31.348  3941  3987 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: battery_event.timestamp_millis (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1701)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1570)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at xt.g(PG:10)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at com.google.android.apps.turbo.nudges.broadcasts.BatteryHistoryLoggerJobService.g(PG:24)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at com.google.android.apps.turbo.nudges.broadcasts.BatteryHistoryLoggerJobService.d(PG:16)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at xr.run(Unknown Source:3)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-09 13:33:31.348  3941  3987 E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:923)

**Comment by herndlm** [comment]
I have the same problem on an A12 rom where the google go cam was pre-installed but I disabled and then removed it to use open camera. With the google go cam it was working, but with open camera it is not anymore.
I also can't seem to find default camera app settings. Any hints?

**Comment by mrjfilippo** [comment]
Same issue also with A12 rom and likewise, not sure where the setting for default cam would be. When I double tap the power button, it opens gcam. The ROM (Elixir Redmi Note Pro 7) didn't come with a default camera app this time.

**Comment by mrjfilippo** [comment]
Now I went back to PixelExperience ROM, didn't remove the default Camera Go application and it is working normally.
