### ISSUE TITLE
Crash if attached file is deleted before sending

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#4163]
2.9.13+fcr, Android 11 AOSP

I can repro:
* 1:1 chat
* Attach images
* choose 4 of the recent ones from the document picker (they'll need to be resized; don't select via an app just use the Android file thing)
* _don't send yet_
* open one in gallery from the input field
* in gallery delete the file
* hit back
* try to send
* crash

Trace via Scoop:
```
FATAL EXCEPTION: main
Process: eu.siacs.conversations, PID: 8858
java.lang.SecurityException: UID 10165 does not have permission to content://media/external/images/media/72328 [user 0]
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3696)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1725)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at android.app.Activity.startActivity(Activity.java:5658)
	at android.app.Activity.startActivity(Activity.java:5611)
	at eu.siacs.conversations.ui.adapter.MediaPreviewAdapter.view(MediaPreviewAdapter.java:77)
	at eu.siacs.conversations.ui.adapter.MediaPreviewAdapter.lambda$onBindViewHolder$1(MediaPreviewAdapter.java:68)
	at eu.siacs.conversations.ui.adapter.-$$Lambda$MediaPreviewAdapter$CS97QIm0yYJBXLXyf46Zh_luK9Y.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28309)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1283)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:624)
	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:117)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1440)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:530)
```

**Comment by licaon-kter** [comment]
If while in document selector one chooses the gallery app, eg. Simple Gallery Pro and attaches from there, it will not crash, it copes with the missing file:
```
java.lang.SecurityException: UID 10165 does not have permission to content://media/external/images/media/72339 [user 0]
     at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
     at android.os.Parcel.createException(Parcel.java:2357)
     at android.os.Parcel.readException(Parcel.java:2340)
     at android.os.Parcel.readException(Parcel.java:2282)
     at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:5841)
     at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1700)
     at android.app.ContextImpl.startService(ContextImpl.java:1670)
     at android.content.ContextWrapper.startService(ContextWrapper.java:720)
     at android.content.ContextWrapper.startService(ContextWrapper.java:720)
     at eu.siacs.conversations.ui.XmppActivity.delegateUriPermissionsToService(XmppActivity.java:560)
     at eu.siacs.conversations.ui.ConversationFragment.attachImageToConversation(ConversationFragment.java:698)
     at eu.siacs.conversations.ui.ConversationFragment.lambda$commitAttachments$1(ConversationFragment.java:883)
     at eu.siacs.conversations.ui.ConversationFragment.lambda$commitAttachments$1$ConversationFragment(Unknown Source:0)
     at eu.siacs.conversations.ui.-$$Lambda$ConversationFragment$dNXopg4AXvFfqlulm9b2iO3M-C4.onPresenceSelected(Unknown Source:4)
     at eu.siacs.conversations.ui.ConversationFragment.commitAttachments(ConversationFragment.java:896)
     at eu.siacs.conversations.ui.ConversationFragment.sendMessage(ConversationFragment.java:728)
     at eu.siacs.conversations.ui.ConversationFragment.access$1300(ConversationFragment.java:139)
     at eu.siacs.conversations.ui.ConversationFragment$14.onClick(ConversationFragment.java:457)
     at android.view.View.performClick(View.java:7448)
     at android.view.View.performClickInternal(View.java:7425)
     at android.view.View.access$3600(View.java:810)
     at android.view.View$PerformClick.run(View.java:28309)
     at android.os.Handler.handleCallback(Handler.java:938)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:223)
     at android.app.ActivityThread.main(ActivityThread.java:7705)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: android.os.RemoteException: Remote stack trace:
     at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1283)
     at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:624)
     at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:117)
     at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1440)
     at com.android.server.am.ActiveServices.startServiceLocked(ActiveServices.java:672)

unable to detect image bounds
java.io.FileNotFoundException: java.io.FileNotFoundException: No item at content://media/external/images/media/72339
     at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
     at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:781)
     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1985)
     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
     at android.content.ContentResolver.openInputStream(ContentResolver.java:1477)
     at eu.siacs.conversations.persistance.FileBackend.unusualBounds(FileBackend.java:800)
     at eu.siacs.conversations.services.XmppConnectionService.attachImageToConversation(XmppConnectionService.java:580)
     at eu.siacs.conversations.ui.ConversationFragment.attachImageToConversation(ConversationFragment.java:699)
     at eu.siacs.conversations.ui.ConversationFragment.lambda$commitAttachments$1(ConversationFragment.java:883)
     at eu.siacs.conversations.ui.ConversationFragment.lambda$commitAttachments$1$ConversationFragment(Unknown Source:0)
     at eu.siacs.conversations.ui.-$$Lambda$ConversationFragment$dNXopg4AXvFfqlulm9b2iO3M-C4.onPresenceSelected(Unknown Source:4)
     at eu.siacs.conversations.ui.ConversationFragment.commitAttachments(ConversationFragment.java:896)
     at eu.siacs.conversations.ui.ConversationFragment.sendMessage(ConversationFragment.java:728)
     at eu.siacs.conversations.ui.ConversationFragment.access$1300(ConversationFragment.java:139)
     at eu.siacs.conversations.ui.ConversationFragment$14.onClick(ConversationFragment.java:457)
     at android.view.View.performClick(View.java:7448)
     at android.view.View.performClickInternal(View.java:7425)
     at android.view.View.access$3600(View.java:810)
     at android.view.View$PerformClick.run(View.java:28309)
     at android.os.Handler.handleCallback(Handler.java:938)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:223)
     at android.app.ActivityThread.main(ActivityThread.java:7705)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```
