### ISSUE TITLE
Some video files are not compressed to 720p

### ISSUE THREAD

**Issue by licaon-kter** [iNPUTmice/Conversations#4167]
2.9.13 Play or 2.9.12 Quicksy

One Plus Android 11 or Huawei P9 Lite Android 7 (iirc)

I can provide an offending file privately.

Logcat
```
D conversations: AxolotlService (convuser@mydomain.tld): Finding devices without session for contact@mydomain.tld
W conversations: AxolotlService (convuser@mydomain.tld): Have no target devices in PEP!
I MediaProvider: Using lower FS for /storage/emulated/0/Conversations/Media/Conversations Videos/9bf70fc7-26ba-4d6d-be9d-d325eb53b4b5.mp4
D conversations: do not consider video file with min width larger than 720 for size check
D conversations: ConversationsActivity.commitAttachments() - attaching file to conversations. CHOOSE_FILE/RECORD_VOICE/RECORD_VIDEO
D conversations: attachFile: type=2
D conversations: counterpart=null
D conversations: guessMimeTypeFromUriAndMime content://media/external/video/media/72805 and mime=video/mp4
D conversations: processing file as video
D conversations: ForegroundService: on
D conversations: received uri permission for content://media/external/video/media/72805
I MediaProvider: Using lower FS for /storage/emulated/0/Conversations/Media/Conversations Videos/9bf70fc7-26ba-4d6d-be9d-d325eb53b4b5.mp4
D conversations: ignoring execution exception. Should get handled by onTranscodeFiled() instead
D conversations: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: extractor does not contain video and/or audio tracks.
D conversations:         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
D conversations:         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
D conversations:         at eu.siacs.conversations.services.AttachFileToConversationRunnable.processAsVideo(AttachFileToConversationRunnable.java:103)
D conversations:         at eu.siacs.conversations.services.AttachFileToConversationRunnable.run(AttachFileToConversationRunnable.java:166)
D conversations:         at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
D conversations:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D conversations:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D conversations:         at java.lang.Thread.run(Thread.java:923)
D conversations: Caused by: java.lang.IllegalArgumentException: extractor does not contain video and/or audio tracks.
D conversations:         at net.ypresto.androidtranscoder.utils.MediaExtractorUtils.getFirstVideoAndAudioTrack(MediaExtractorUtils.java:59)
D conversations:         at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.setupTrackTranscoders(MediaTranscoderEngine.java:164)
D conversations:         at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:99)
D conversations:         at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:184)
D conversations:         at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:166)
D conversations:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D conversations:         ... 3 more
D conversations: ForegroundService: on
D conversations: video transcoding failed
D conversations: java.lang.IllegalArgumentException: extractor does not contain video and/or audio tracks.
D conversations:         at net.ypresto.androidtranscoder.utils.MediaExtractorUtils.getFirstVideoAndAudioTrack(MediaExtractorUtils.java:59)
D conversations:         at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.setupTrackTranscoders(MediaTranscoderEngine.java:164)
D conversations:         at net.ypresto.androidtranscoder.engine.MediaTranscoderEngine.transcodeVideo(MediaTranscoderEngine.java:99)
D conversations:         at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:184)
D conversations:         at net.ypresto.androidtranscoder.MediaTranscoder$4.call(MediaTranscoder.java:166)
D conversations:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D conversations:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D conversations:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D conversations:         at java.lang.Thread.run(Thread.java:923)
D conversations: send file message
D conversations: using 12-byte IV for file transmission
D conversations: uploading file to https://up.mydomain.tld/hash/hash/name.mp4?v=hash
```

**Comment by licaon-kter** [comment]
New log with 3075833ab3812f7dbce8886fd750950fb376dd48
```
I MediaProvider: Redacting with new FUSE for /storage/emulated/0/Conversations/Media/Conversations Videos/9bf70fc7-26ba-4d6d-be9d-d325eb53b4b5.mp4
D myconversations3: do not consider video file with min width larger than 720 for size check
D myconversations3: ConversationsActivity.commitAttachments() - attaching file to conversations. CHOOSE_FILE/RECORD_VOICE/RECORD_VIDEO
D myconversations3: attachFile: type=2
D myconversations3: counterpart=null
D myconversations3: guessMimeTypeFromUriAndMime content://media/external/video/media/72805 and mime=video/mp4
D myconversations3: processing file as video
D myconversations3: ForegroundService: on
D myconversations3: received uri permission for content://media/external/video/media/72805
I MediaProvider: Redacting with new FUSE for /storage/emulated/0/Conversations/Media/Conversations Videos/9bf70fc7-26ba-4d6d-be9d-d325eb53b4b5.mp4
I MediaProvider: Redacting with new FUSE for /storage/emulated/0/Conversations/Media/Conversations Videos/9bf70fc7-26ba-4d6d-be9d-d325eb53b4b5.mp4
D myconversations3: ignoring execution exception. Should get handled by onTranscodeFiled() instead
D myconversations3: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: No retriever available
D myconversations3:      at java.util.concurrent.FutureTask.report(FutureTask.java:123)
D myconversations3:      at java.util.concurrent.FutureTask.get(FutureTask.java:193)
D myconversations3:      at eu.siacs.conversations.services.AttachFileToConversationRunnable.processAsVideo(AttachFileToConversationRunnable.java:109)
D myconversations3:      at eu.siacs.conversations.services.AttachFileToConversationRunnable.run(AttachFileToConversationRunnable.java:172)
D myconversations3:      at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
D myconversations3:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D myconversations3:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D myconversations3:      at java.lang.Thread.run(Thread.java:923)
D myconversations3: Caused by: java.lang.IllegalStateException: No retriever available
D myconversations3:      at android.media.MediaMetadataRetriever.nativeExtractMetadata(Native Method)
D myconversations3:      at android.media.MediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.java:399)
D myconversations3:      at com.otaliastudios.transcoder.source.DefaultDataSource.getLocation(DefaultDataSource.java:253)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:54)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:27)
D myconversations3:      at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
D myconversations3:      at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
D myconversations3:      at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
D myconversations3:      at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:133)
D myconversations3:      at kotlin.sequences.SequencesKt.firstOrNull(Unknown Source:0)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.<init>(DefaultTranscodeEngine.kt:54)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:32)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
D myconversations3:      at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
D myconversations3:      at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
D myconversations3:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D myconversations3:      ... 3 more
D myconversations3: ForegroundService: on
D myconversations3: video transcoding failed
D myconversations3: java.lang.IllegalStateException: No retriever available
D myconversations3:      at android.media.MediaMetadataRetriever.nativeExtractMetadata(Native Method)
D myconversations3:      at android.media.MediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.java:399)
D myconversations3:      at com.otaliastudios.transcoder.source.DefaultDataSource.getLocation(DefaultDataSource.java:253)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:54)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine$location$1.invoke(DefaultTranscodeEngine.kt:27)
D myconversations3:      at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
D myconversations3:      at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
D myconversations3:      at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
D myconversations3:      at kotlin.sequences.SequencesKt___SequencesKt.firstOrNull(_Sequences.kt:133)
D myconversations3:      at kotlin.sequences.SequencesKt.firstOrNull(Unknown Source:0)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.DefaultTranscodeEngine.<init>(DefaultTranscodeEngine.kt:54)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine$Companion.transcode(TranscodeEngine.kt:32)
D myconversations3:      at com.otaliastudios.transcoder.internal.transcode.TranscodeEngine.transcode(Unknown Source:2)
D myconversations3:      at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:102)
D myconversations3:      at com.otaliastudios.transcoder.Transcoder$1.call(Transcoder.java:99)
D myconversations3:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
D myconversations3:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
D myconversations3:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
D myconversations3:      at java.lang.Thread.run(Thread.java:923)
D myconversations3: send file message
```

**Comment by licaon-kter** [comment]
Reading https://github.com/natario1/Transcoder/issues/146 and https://github.com/natario1/Transcoder/issues/138 maybe v0.9.1 works, I'll try to rebuild with that version instead of latest v0.10.3

**Comment by licaon-kter** [comment]
Using v0.9.1 instead of v0.10.3 compresses the video as expected, yay
