### ISSUE TITLE
Crash on startup after upgrade to 2.10.0

### ISSUE THREAD

**Issue by gjedeer** [iNPUTmice/Conversations#4170]
I can't start the app after upgrade to 2.10.0, it crashes immediately. Had to downgrade to 2.9 to be able to use it normally.

I also have a Matlog dump including device version, kernel etc, I can share it privately if you tell me the email address.

LineageOS 15.1 on Samsung SM-G960F.

```
java.lang.RuntimeException: Unable to create service eu.siacs.conversations.services.XmppConnectionService: android.database.sqlite.SQLiteException: vtable constructor failed: messages_index (code 1)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3349)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.database.sqlite.SQLiteException: vtable constructor failed: messages_index (code 1)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:735)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1755)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1682)
	at eu.siacs.conversations.persistance.DatabaseBackend.onUpgrade(DatabaseBackend.java:580)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:338)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:262)
	at eu.siacs.conversations.persistance.DatabaseBackend.getAccounts(DatabaseBackend.java:961)
	at eu.siacs.conversations.services.XmppConnectionService.onCreate(XmppConnectionService.java:1136)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
	... 8 more
```

**Comment by gjedeer** [comment]
Just to confirm what I was asked in the chat: 

```
130|starlte:/ # /system/bin/sqlite3                     
SQLite version 3.19.4 2018-12-19 17:05:48
```

**Comment by gjedeer** [comment]
I've pulled the history file to my computer with adb. I've copied the SQL statement from Conversations source code and ran it. It still fails with the same error on my computer:

```
$ sqlite3 history_cp 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> CREATE VIRTUAL TABLE messages_index USING fts4 (uuid,body,notindexed="uuid",content="messages",tokenize='unicode61');
Error: vtable constructor failed: messages_index
sqlite> select count(1) from messages;
481277
sqlite> PRAGMA table_info(messages);
0|uuid|TEXT|0||1
1|conversationUuid|TEXT|0||0
2|timeSent|NUMBER|0||0
3|counterpart|TEXT|0||0
4|trueCounterpart|TEXT|0||0
5|body|TEXT|0||0
6|encryption|NUMBER|0||0
7|status|NUMBER|0||0
8|type|NUMBER|0||0
9|relativeFilePath|TEXT|0||0
10|serverMsgId|TEXT|0||0
11|axolotl_fingerprint|TEXT|0||0
12|carbon|INTEGER|0||0
13|edited|TEXT|0||0
14|read|NUMBER|0|1|0
15|oob|INTEGER|0||0
16|errorMsg|TEXT|0||0
17|readByMarkers|TEXT|0||0
18|markable|NUMBER|0|0|0
19|remoteMsgId|TEXT|0||0
20|deleted|NUMBER|0|0|0
21|bodyLanguage||0||0
```

I've also tried to make a dump and import it, but the query still fails:

```
➜  tmp sqlite3 history_cp .dump | sqlite3 history_cp2
➜  tmp sqlite3 history_cp2
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> CREATE VIRTUAL TABLE messages_index USING fts4 (uuid,body,notindexed="uuid",content="messages",tokenize='unicode61');
Error: vtable constructor failed: messages_index
sqlite> 
```

**Comment by gjedeer** [comment]
As advised on the MUC, doing the following and then upgrading again helped:

```
sqlite> drop table messages_index_docsize;
sqlite> drop table messages_index_segdir;
sqlite> drop table messages_index_segments;
sqlite> drop table messages_index_stat;
```

**Comment by XRevan86** [comment]
Now that SQLite revealed to be a lot less reliable than it should be with dropping an FTS vtable and transaction integrity, I think the migration code should be reshaped like this:
```diff
--- a/src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
+++ b/src/main/java/eu/siacs/conversations/persistance/DatabaseBackend.java
@@ -5,6 +5,7 @@ import android.content.Context;
 import android.database.Cursor;
 import android.database.DatabaseUtils;
 import android.database.sqlite.SQLiteDatabase;
+import android.database.sqlite.SQLiteException;
 import android.database.sqlite.SQLiteOpenHelper;
 import android.os.Environment;
 import android.os.SystemClock;
@@ -576,14 +577,24 @@ public class DatabaseBackend extends SQL
             db.beginTransaction();
             db.execSQL("DROP TRIGGER IF EXISTS after_message_insert;");
             db.execSQL("DROP TRIGGER IF EXISTS after_message_update;");
+            db.execSQL("DROP TRIGGER IF EXISTS after_message_delete;");
             db.execSQL("DROP TABLE IF EXISTS messages_index;");
+            // a hack that should not be necessary, but
+            // there was at least one occurence when SQLite failed at this
+            db.execSQL("DROP TABLE IF EXISTS messages_index_docsize;");
+            db.execSQL("DROP TABLE IF EXISTS messages_index_segdir;");
+            db.execSQL("DROP TABLE IF EXISTS messages_index_segments;");
+            db.execSQL("DROP TABLE IF EXISTS messages_index_stat;");
+            db.setTransactionSuccessful();
+            db.endTransaction();
+            db.beginTransaction();
             db.execSQL(CREATE_MESSAGE_INDEX_TABLE);
             db.execSQL(CREATE_MESSAGE_INSERT_TRIGGER);
             db.execSQL(CREATE_MESSAGE_UPDATE_TRIGGER);
             db.execSQL(CREATE_MESSAGE_DELETE_TRIGGER);
-            requiresMessageIndexRebuild = true;
             db.setTransactionSuccessful();
             db.endTransaction();
+            requiresMessageIndexRebuild = true;
         }
     }
 
````

**Comment by herbsmn** [comment]
My phone's entire operating system stopped booting properly after F-Droid auto updated Conversations 2.10.0.

I had to adb into the phone via the Recovery and uninstall Conversations in order to get the operating system to boot again.

I'm running Replicant 6.0 0004 rc1 from https://replicant.us
