### ISSUE TITLE
"failure to connect to socks server" while sending a picture through tor

### ISSUE THREAD

**Issue by FilLupin** [iNPUTmice/Conversations#4251]
Hello,
thank you for developing this app. :)

I got an issue since I installed it: when sending a picture through tor (orbot 16.4.1-RC-2-tor.0.4.4.6 / Tor 0.4.4.6-openssl1.1.1g) on android 4.2.2 and conversations 2.9.3+fcr, I got the following error: `failure to connect to socks server`.
I know this is an old android version, this is why I am stuck with old versions of apps.

Here is the logcat output:
```
--------- beginning of /dev/log/main
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 443 is already being handled; removing. 
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 5222 is already being handled; removing. 
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 443 is already being handled; removing. 
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 5222 is already being handled; removing. 
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 443 is already being handled; removing. 
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 5222 is already being handled; removing. 
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 443 is already being handled; removing. 
D/Orbot   ( 2959): DEBUG: circuit_remove_handled_ports: Port 5222 is already being handled; removing. 
D/conversations( 2665): send file message
D/conversations( 2665): using 12-byte IV for file transmission
D/Orbot   ( 2959): DEBUG: conn_read_callback: socket 18 wants to read. 
D/Orbot   ( 2959): DEBUG: read_to_chunk: Read 242 bytes. 242 on inbuf. 
D/Orbot   ( 2959): DEBUG: circuit_consider_stop_edge_reading: considering layer_hint->package_window 969 
D/Orbot   ( 2959): DEBUG: circuit_consider_stop_edge_reading: considering layer_hint->package_window 969 
D/Orbot   ( 2959): DEBUG: connection_edge_package_raw_inbuf: 18: Packaging 242 bytes (0 waiting). 
D/Orbot   ( 2959): DEBUG: relay_send_command_from_edge_: delivering 2 cell forward. 
D/Orbot   ( 2959): DEBUG: relay_encrypt_cell_outbound: encrypting a layer of the relay cell. 
D/Orbot   ( 2959): DEBUG: relay_encrypt_cell_outbound: encrypting a layer of the relay cell. 
D/Orbot   ( 2959): DEBUG: relay_encrypt_cell_outbound: encrypting a layer of the relay cell. 
D/Orbot   ( 2959): DEBUG: append_cell_to_circuit_queue: Made a circuit active. 
D/Orbot   ( 2959): DEBUG: scheduler_set_channel_state: chan 5 changed from scheduler state WAITING_FOR_CELLS to PENDING 
D/Orbot   ( 2959): DEBUG: sendme_note_circuit_data_packaged: Circuit package_window now 968. 
D/Orbot   ( 2959): DEBUG: sendme_note_stream_data_packaged: Stream package_window now 468. 
D/Orbot   ( 2959): DEBUG: connection_edge_package_raw_inbuf: conn->package_window is now 468 
D/Orbot   ( 2959): DEBUG: circuit_consider_stop_edge_reading: considering layer_hint->package_window 968 
D/Orbot   ( 2959): DEBUG: scheduler_evt_callback: Scheduler event callback called 
D/Orbot   ( 2959): DEBUG: update_socket_info: chan=5 updated socket info, limit: 15456, cwnd: 6, unacked: 0, notsent: 0, mss: 1288 
D/Orbot   ( 2959): DEBUG: kist_scheduler_run: Running the scheduler. 1 channels pending 
D/Orbot   ( 2959): DEBUG: outbuf_table_add: scheduler init outbuf info for chan=5 
D/Orbot   ( 2959): DEBUG: channel_write_packed_cell: Writing 0x2b310208 to channel 0x2b2e5d50 with global ID 5 
D/Orbot   ( 2959): DEBUG: channel_flush_from_first_active_circuit: Made a circuit inactive. 
D/Orbot   ( 2959): DEBUG: update_socket_written: chan=5 wrote 543 bytes, old was 0 
D/Orbot   ( 2959): DEBUG: scheduler_set_channel_state: chan 5 changed from scheduler state PENDING to WAITING_FOR_CELLS 
D/Orbot   ( 2959): DEBUG: channel_write_to_kernel: Writing 514 bytes to kernel for chan 5 
D/Orbot   ( 2959): DEBUG: flush_chunk_tls: flushed 514 bytes, 0 ready to flush, 0 remain. 
D/Orbot   ( 2959): DEBUG: connection_handle_write_impl: After TLS write of 514: 0 read, 536 written 
D/Orbot   ( 2959): DEBUG: free_outbuf_info_by_ent: Freeing outbuf table entry from chan=5 
D/Orbot   ( 2959): DEBUG: kist_scheduler_run: len pending=0, len to_readd=-1 
I/Choreographer( 2665): Skipped 35 frames!  The application may be doing too much work on its main thread.
D/Orbot   ( 2959): DEBUG: conn_read_callback: socket 16 wants to read. 
D/Orbot   ( 2959): DEBUG: connection_buf_read_from_socket: 16: starting, inbuf_datalen 0 (0 pending in tls object). at_most 16448. 
D/Orbot   ( 2959): DEBUG: connection_buf_read_from_socket: After TLS read of 1028: 1050 read, 0 written 
D/Orbot   ( 2959): DEBUG: connection_or_process_cells_from_inbuf: 16: starting, inbuf_datalen 1028 (0 pending in tls object). 
D/Orbot   ( 2959): DEBUG: channel_process_cell: Processing incoming cell_t 0xbefff168 for channel 0x2b2e5d50 (global ID 5) 
D/Orbot   ( 2959): DEBUG: circuit_get_by_circid_channel_impl: circuit_get_by_circid_channel_impl() returning circuit 0x2b05bd78 for circ_id 4070183511, channel ID 5 (0x2b2e5d50) 
D/Orbot   ( 2959): DEBUG: relay_lookup_conn: found conn for stream 313. 
D/Orbot   ( 2959): DEBUG: circuit_receive_relay_cell: Sending to origin. 
D/Orbot   ( 2959): DEBUG: connection_edge_process_relay_cell: Now seen 2995 relay cells here (command 2, stream 313). 
D/Orbot   ( 2959): DEBUG: sendme_circuit_data_received: Circuit deliver_window now 933. 
D/Orbot   ( 2959): DEBUG: connection_or_process_cells_from_inbuf: 16: starting, inbuf_datalen 514 (0 pending in tls object). 
D/Orbot   ( 2959): DEBUG: channel_process_cell: Processing incoming cell_t 0xbefff168 for channel 0x2b2e5d50 (global ID 5) 
D/Orbot   ( 2959): DEBUG: circuit_get_by_circid_channel_impl: circuit_get_by_circid_channel_impl() returning circuit 0x2b05bd78 for circ_id 4070183511, channel ID 5 (0x2b2e5d50) 
D/Orbot   ( 2959): DEBUG: relay_lookup_conn: found conn for stream 313. 
D/Orbot   ( 2959): DEBUG: circuit_receive_relay_cell: Sending to origin. 
D/Orbot   ( 2959): DEBUG: connection_edge_process_relay_cell: Now seen 2996 relay cells here (command 2, stream 313). 
D/Orbot   ( 2959): DEBUG: sendme_circuit_data_received: Circuit deliver_window now 932. 
D/Orbot   ( 2959): DEBUG: connection_or_process_cells_from_inbuf: 16: starting, inbuf_datalen 0 (0 pending in tls object). 
D/conversations( 2665): uploading to https://WEBSITE.org/upload/cfee2913ce572d9ebb0a968a72b035ab87396582/E4xfTeGg2FgR1zwfvorI/JzHGAlfnQuyaAw6yeWM22w.jpg w/ read timeout of 56s
D/Orbot   ( 2959): DEBUG: conn_write_callback: socket 18 wants to write. 
D/Orbot   ( 2959): DEBUG: conn_read_callback: socket 18 wants to read. 
D/Orbot   ( 2959): DEBUG: read_to_chunk: Read 56 bytes. 56 on inbuf. 
D/Orbot   ( 2959): DEBUG: circuit_consider_stop_edge_reading: considering layer_hint->package_window 968 
D/Orbot   ( 2959): DEBUG: circuit_consider_stop_edge_reading: considering layer_hint->package_window 968 
D/Orbot   ( 2959): DEBUG: connection_edge_package_raw_inbuf: 18: Packaging 56 bytes (0 waiting). 
D/Orbot   ( 2959): DEBUG: relay_send_command_from_edge_: delivering 2 cell forward. 
D/Orbot   ( 2959): DEBUG: relay_encrypt_cell_outbound: encrypting a layer of the relay cell. 
D/Orbot   ( 2959): DEBUG: relay_encrypt_cell_outbound: encrypting a layer of the relay cell. 
D/Orbot   ( 2959): DEBUG: relay_encrypt_cell_outbound: encrypting a layer of the relay cell. 
D/Orbot   ( 2959): DEBUG: append_cell_to_circuit_queue: Made a circuit active. 
D/Orbot   ( 2959): DEBUG: scheduler_set_channel_state: chan 5 changed from scheduler state WAITING_FOR_CELLS to PENDING 
D/Orbot   ( 2959): DEBUG: sendme_note_circuit_data_packaged: Circuit package_window now 967. 
D/Orbot   ( 2959): DEBUG: sendme_note_stream_data_packaged: Stream package_window now 467. 
D/Orbot   ( 2959): DEBUG: connection_edge_package_raw_inbuf: conn->package_window is now 467 
D/Orbot   ( 2959): DEBUG: circuit_consider_stop_edge_reading: considering layer_hint->package_window 967 
D/Orbot   ( 2959): DEBUG: scheduler_evt_callback: Scheduler event callback called 
D/Orbot   ( 2959): DEBUG: update_socket_info: chan=5 updated socket info, limit: 15456, cwnd: 6, unacked: 0, notsent: 0, mss: 1288 
D/Orbot   ( 2959): DEBUG: kist_scheduler_run: Running the scheduler. 1 channels pending 
D/Orbot   ( 2959): DEBUG: outbuf_table_add: scheduler init outbuf info for chan=5 
D/Orbot   ( 2959): DEBUG: channel_write_packed_cell: Writing 0x2b310208 to channel 0x2b2e5d50 with global ID 5 
D/Orbot   ( 2959): DEBUG: channel_flush_from_first_active_circuit: Made a circuit inactive. 
D/Orbot   ( 2959): DEBUG: update_socket_written: chan=5 wrote 543 bytes, old was 0 
D/Orbot   ( 2959): DEBUG: scheduler_set_channel_state: chan 5 changed from scheduler state PENDING to WAITING_FOR_CELLS 
D/Orbot   ( 2959): DEBUG: channel_write_to_kernel: Writing 514 bytes to kernel for chan 5 
D/Orbot   ( 2959): DEBUG: flush_chunk_tls: flushed 514 bytes, 0 ready to flush, 0 remain. 
D/Orbot   ( 2959): DEBUG: connection_handle_write_impl: After TLS write of 514: 0 read, 536 written 
D/Orbot   ( 2959): DEBUG: free_outbuf_info_by_ent: Freeing outbuf table entry from chan=5 
D/Orbot   ( 2959): DEBUG: kist_scheduler_run: len pending=0, len to_readd=-1 
D/Orbot   ( 2959): DEBUG: conn_read_callback: socket 7 wants to read. 
D/Orbot   ( 2959): DEBUG: connection_handle_listener_read: Connection accepted on socket 15 (child of fd 7). 
D/Orbot   ( 2959): INFO: connection_handle_listener_read: New SOCKS connection opened from 127.0.0.1. 
D/Orbot   ( 2959): DEBUG: connection_add_impl: new conn type Socks, socket 15, address 127.0.0.1, n_conns 10. 
D/Orbot   ( 2959): DEBUG: conn_read_callback: socket 15 wants to read. 
D/Orbot   ( 2959): DEBUG: read_to_chunk: Read 16 bytes. 16 on inbuf. 
D/Orbot   ( 2959): DEBUG: connection_ap_handshake_process_socks: entered. 
D/Orbot   ( 2959): StreamStatus (50): NEW
W/System.err( 2665): java.io.IOException: Failure to connect to SOCKS server
D/Orbot   ( 2959): DEBUG: connection_ap_handshake_rewrite: Client asked for 127.0.0.1:9050 
D/Orbot   ( 2959): WARN: Rejecting SOCKS request for anonymous connection to private address 127.0.0.1. [1 similar message(s) suppressed in last 300 seconds] 
D/Orbot   ( 2959): StreamStatus (50): FAILED
D/Orbot   ( 2959): DEBUG: conn_close_if_marked: Cleaning up connection (fd 15). 
D/Orbot   ( 2959): StreamStatus (50): CLOSED
D/Orbot   ( 2959): DEBUG: connection_remove: removing socket 15 (type Socks), n_conns now 10 
D/Orbot   ( 2959): DEBUG: connection_free_minimal: closing fd 15. 
D/Orbot   ( 2959): DEBUG: conn_read_callback: socket 7 wants to read. 
D/Orbot   ( 2959): DEBUG: connection_handle_listener_read: Connection accepted on socket 15 (child of fd 7). 
D/Orbot   ( 2959): INFO: connection_handle_listener_read: New SOCKS connection opened from 127.0.0.1. 
D/Orbot   ( 2959): DEBUG: connection_add_impl: new conn type Socks, socket 15, address 127.0.0.1, n_conns 10. 
D/Orbot   ( 2959): DEBUG: conn_read_callback: socket 15 wants to read. 
D/Orbot   ( 2959): DEBUG: read_to_chunk: Read 16 bytes. 16 on inbuf. 
D/Orbot   ( 2959): DEBUG: connection_ap_handshake_process_socks: entered. 
D/Orbot   ( 2959): StreamStatus (51): NEW
D/Orbot   ( 2959): DEBUG: connection_ap_handshake_rewrite: Client asked for 127.0.0.1:9050 
D/Orbot   ( 2959): StreamStatus (51): FAILED
D/Orbot   ( 2959): DEBUG: conn_close_if_marked: Cleaning up connection (fd 15). 
D/Orbot   ( 2959): StreamStatus (51): CLOSED
D/Orbot   ( 2959): DEBUG: connection_remove: removing socket 15 (type Socks), n_conns now 10 
D/Orbot   ( 2959): DEBUG: connection_free_minimal: closing fd 15. 
W/System.err( 2665): 	at java.net.PlainSocketImpl.socksRequestConnection(PlainSocketImpl.java:345)
W/System.err( 2665): 	at java.net.PlainSocketImpl.socksConnect(PlainSocketImpl.java:329)
W/System.err( 2665): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:190)
W/System.err( 2665): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
W/System.err( 2665): 	at java.net.Socket.connect(Socket.java:842)
W/System.err( 2665): 	at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
W/System.err( 2665): 	at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
W/System.err( 2665): 	at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
W/System.err( 2665): 	at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
W/System.err( 2665): 	at libcore.net.http.HttpConnection.connect(HttpConnection.java:98)
W/System.err( 2665): 	at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
W/System.err( 2665): 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:461)
W/System.err( 2665): 	at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:442)
W/System.err( 2665): 	at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
W/System.err( 2665): 	at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
W/System.err( 2665): 	at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:81)
W/System.err( 2665): 	at libcore.net.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:165)
W/System.err( 2665): 	at eu.siacs.conversations.http.HttpUploadConnection.upload(HttpUploadConnection.java:187)
W/System.err( 2665): 	at eu.siacs.conversations.http.HttpUploadConnection.access$300(HttpUploadConnection.java:30)
W/System.err( 2665): 	at eu.siacs.conversations.http.HttpUploadConnection$1.lambda$success$0(HttpUploadConnection.java:139)
W/System.err( 2665): 	at eu.siacs.conversations.http.-$$Lambda$HttpUploadConnection$1$ektaHXFqxgW3UQRYD5-n6pWZA0w.run(lambda)
W/System.err( 2665): 	at java.lang.Thread.run(Thread.java:856)
D/conversations( 2665): http upload failed Failure to connect to SOCKS server
```

Do you know how I could solve this?

Regards,

**Comment by iNPUTmice** [comment]
You can backport this commit: https://github.com/iNPUTmice/Conversations/commit/914ea9c398853b0b3da7df68bd55274ea5f74db0

**Comment by FilLupin** [comment]
Thank you, this is my first build on android, could you help me by giving me some instructions about how to do this?
Cheers

**Comment by licaon-kter** [comment]
@FilLupin see Readme, use Android Studio or fdroidserver

**Comment by FilLupin** [comment]
Thank you, I'll be unable to address this for the moment (my app crashed) but I sure will look at it once repaired.

Cheers.
