### ISSUE TITLE
Backup restoration does not work due to sqlite UNIQUE error

### ISSUE THREAD

**Issue by ValdikSS** [iNPUTmice/Conversations#4270]
I've created backup on one device with 2.10.2+pcr and trying to import it to another device, also running 2.10.2+pcr.
Backup could not be restored with the following error in logcat:

```
01-24 14:31:32.650 23575 23640 D conversations: error restoring backup content://com.android.providers.downloads.documents/document/34
01-24 14:31:32.650 23575 23640 D conversations: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: messages.uuid (code 1555 SQLITE_CONSTRAINT_PRIMARYKEY)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:832)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:756)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1824)
01-24 14:31:32.650 23575 23640 D conversations:         at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1751)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService.importBackup(ImportBackupService.java:260)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService.lambda$onStartCommand$0(ImportBackupService.java:108)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService.$r8$lambda$_Gblybgouv1Yt7P2F13nA3J9Xfw(Unknown Source:0)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.services.ImportBackupService$$ExternalSyntheticLambda0.run(Unknown Source:6)
01-24 14:31:32.650 23575 23640 D conversations:         at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
01-24 14:31:32.650 23575 23640 D conversations:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-24 14:31:32.650 23575 23640 D conversations:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-24 14:31:32.650 23575 23640 D conversations:         at java.lang.Thread.run(Thread.java:919)
```

**Comment by licaon-kter** [comment]
Device? Android version?

**Comment by ValdikSS** [comment]
Android 10 on both. Unihertz Titan where the backup has been created, LG V50 where I'm trying to restore.

**Comment by sonicnkt** [comment]
Might be having the same issue tho im not sure.
Trying to restore a backup made on Android 9 with 2.10.2.1 (Fdroid). Also on a Unihertz Titan.  
Now i want to restore this on a Pixel 5 running Android 12 (CalyxOS 3.5.1). After i input the passwords it just says that it couldnt be restored. 
Don't know what else i could try, will gladly provide logs but i would need some guide on how to produce these with android.

**Comment by licaon-kter** [comment]
@sonicnkt does this extract ok on a desktop with ceb2txt?

**Comment by sonicnkt** [comment]
Well i tried to create several backups on the same device.  
Restore or ceb2txt fails with both....  Sadly i have no other synced device were i could try to get a backup from :( 

The old installation still works fine tho, really wonder what is messing it up

**Comment by resoli** [comment]
More or less the same here, with both 2.10.2 f-droid and self-built 2.10.8, LinegeOS 18.1 on OP3T. 

ceb2txt fails to restore an account with:

`[SQLITE_ERROR] SQL error or missing database (unrecognized token)`

The 'token' seems part of a message quoting code or commands

Other seven accounts are restoted ok. An old (march 2021) backup of the same account fails but on a different SQL INSERT with quoted code/commands.

**Comment by resoli** [comment]
Stacktrace from ceb2txt on the backup failing restore:
```
Enter password for (redacted)@conversations.im: 
Exception in thread "main" org.sql2o.Sql2oException: Error preparing statement - [SQLITE_ERROR] SQL error or missing database (unrecognized token: "'sudo sysctl -p /etc/sysctl.d/30-peertube-tcp.conf")
	at org.sql2o.Query.buildPreparedStatement(Query.java:439)
	at org.sql2o.Query.buildPreparedStatement(Query.java:421)
	at org.sql2o.Query.executeUpdate(Query.java:652)
	at im.conversations.ceb2txt.Main.main(Main.java:110)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "'sudo sysctl -p /etc/sysctl.d/30-peertube-tcp.conf")
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
	at org.sql2o.Query.buildPreparedStatement(Query.java:434)
	... 3 more
```

**Comment by resoli** [comment]
Stacktrace from ceb2txt on the March 2021 backup (I enclosed triple backquotes in the stacktrace in parenthesis):
```
Enter password for (REDACTED)@conversations.im: 
Exception in thread "main" org.sql2o.Sql2oException: Error preparing statement - [SQLITE_ERROR] SQL error or missing database (unrecognized token: "'> coturn does both
(```)
grep -v ''^#'' /etc/turnserver.conf         ")
	at org.sql2o.Query.buildPreparedStatement(Query.java:439)
	at org.sql2o.Query.buildPreparedStatement(Query.java:421)
	at org.sql2o.Query.executeUpdate(Query.java:652)
	at im.conversations.ceb2txt.Main.main(Main.java:110)
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (unrecognized token: "'> coturn does both
(```)
grep -v ''^#'' /etc/turnserver.conf         ")
	at org.sqlite.core.DB.newSQLException(DB.java:1010)
	at org.sqlite.core.DB.newSQLException(DB.java:1022)
	at org.sqlite.core.DB.throwex(DB.java:987)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:45)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:214)
	at org.sql2o.Query.buildPreparedStatement(Query.java:434)
	... 3 more
```

**Comment by resoli** [comment]
logcat output (account names redacted):
```
07-31 23:06:19.667 D/conversations(10988): attempting to import content://com.android.externalstorage.documents/document/primary%3AConversations%2FBackup%2FJID_NAME_REDACTED%40conversations.im.ceb
07-31 23:06:19.790 D/conversations(10988): directory not found: /storage/emulated/0/Quicksy/Backup
07-31 23:06:26.913 D/conversations(10988): importing backup from content://com.android.externalstorage.documents/document/primary%3AConversations%2FBackup%2FJID_NAME_REDACTED%40conversations.im.ceb
07-31 23:06:26.987 D/conversations(10988): BackupFileHeader{app='Conversations', jid=JID_NAME_REDACTED@conversations.im, timestamp=1659279477390, iv=8918845006f751e44d1fed53, salt=5225288e8a6806f0708b5095ec25e59b}
07-31 23:06:55.344 D/conversations(10988): error restoring backup content://com.android.externalstorage.documents/document/primary%3AConversations%2FBackup%2FJID_NAME_REDACTED%40conversations.im.ceb
07-31 23:06:55.344 D/conversations(10988): android.database.sqlite.SQLiteException: unrecognized token: "'sudo sysctl -p /etc/sysctl.d/30-peertube-tcp.conf" (code 1 SQLITE_ERROR): , while compiling: INSERT INTO messages(uuid,conversationUuid,timeSent,counterpart,trueCounterpart,body,encryption,status,type,relativeFilePath,serverMsgId,axolotl_fingerprint,carbon,edited,read,oob,errorMsg,readByMarkers,markable,deleted,bodyLanguage,remoteMsgId) VALUES('ed803db6-3837-46a8-8ca5-def2a8978193','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617731726077,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'Ok',5,0,0,NULL,1617731726077152,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'ea1d2ddb-8c21-441f-81a2-472cc905b480'),('9b069ba2-b00b-4500-8143-c9cd993c58ea','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617732000808,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'Fatto ',5,0,0,NULL,1617732000555688,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'83442ccd-6d2c-45fa-9efc-7d84c9455e82'),('2ee9c193-d79a-421c-a880-97f535cd92f2','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617732029907,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'Grazie, dopo provo.',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('557ce039-b975-488a-a640-ed7ee24de76a','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617732049881,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'Pruvileged e nesting',5,0,0,NULL,1617732049666827,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'de2a7af9-9707-4079-9d6c-2adf715d4cc2'),('1fa3973b-5419-4ab4-9b82-23120190c36b','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617732063797,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'benone',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('c876246b-8d76-4859-9b87-2426aaf2c558','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617732090855,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'Siamo costosi ma se possiamo facciamo il possibile ',5,0,0,NULL,1617732090640103,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'f8be7fe5-5a85-4b6d-af33-6aff6c8921e3'),('26ac2131-d6be-416d-a400-2263b9daef2c','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617732117417,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,':-)',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('f265ab11-b386-4ab6-ab2e-ea4d0133c76a','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733152220,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'praticamente a posto.
07-31 23:06:55.344 D/conversations(10988): * redis-server systemd unit: ok
07-31 23:06:55.344 D/conversations(10988): * peertube systemd unit: ok',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[{"edited_id":"42bee0fa-82bc-47cf-9579-babd498a7839"},{"edited_id":"232abeaf-97e5-4ad8-9d33-1860b6197422"}]',1,0,NULL,'[]',0,0,NULL,NULL),('31820c82-66b1-4486-b06a-2788e8fdfe6e','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733295983,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'l''unica cosa che manca è:
07-31 23:06:55.344 D/conversations(10988): ```net.core.default_qdisc = fq_codel```',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('c4c801f5-9eff-418c-aa9a-b3ea6d9845f3','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733368150,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'Ok, ma in parole povere? ',5,0,0,NULL,1617733367921841,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'304e8095-a349-4c4d-8410-316df84697ce'),('d42e174c-b508-489b-8428-a8a1d1e085ca','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733413234,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'sudo sysctl -p /etc/sysctl.d/30-peertube-tcp.conf����
07-31 23:06:55.345 D/conversations(10988): sysctl: cannot stat /proc/sys/net/core/default_qdisc: No such file
07-31 23:06:55.345 D/conversations(10988): or directory',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('69e2a4b2-8a2d-499d-b38c-b027ec99d50d','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733450852,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'non c''è quella parte di alberatura.',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('95e25e69-3caf-4e60-a746-4989abdb4c8b','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733523642,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'https://github.com/systemd/systemd/issues/15183',5,0,0,NULL,1617733523426797,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'ebd7e654-f618-4c33-8ec0-8f7cbec82953'),('1e5c1011-3749-4811-9bbc-7b4ef49c83b0','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733550706,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'Non penso sia molto importante, a parte per connessioni client molto lente:
07-31 23:06:55.345 D/conversations(10988): ```
07-31 23:06:55.345 D/conversations(10988): 
07-31 23:06:55.345 D/conversations(10988): # In a video server, we are often sending files to a client
07-31 23:06:55.345 D/conversations(10988): # which can''t accept it as fast as our local network connection
07-31 23:06:55.345 D/conversations(10988): # In a video server, we are often sending files to a client
07-31 23:06:55.345 D/conversations(10988): # which can''t accept it as fast as our local network connection
07-31 23:06:55.345 D/conversations(10988): # could produce packets. To prevent packet loss and buffer bloat,
07-31 23:06:55.345 D/conversations(10988): # it''s especially important to use a modern CoDel scheduler which
07-31 23:06:55.345 D/conversations(10988): # knows how to delay outgoing packets to match slower client links.
07-31 23:06:55.345 D/conversations(10988): 
07-31 23:06:55.345 D/conversations(10988): #ROB: non presente su lxc
07-31 23:06:55.345 D/conversations(10988): net.core.default_qdisc = fq_codel
07-31 23:06:55.345 D/conversations(10988): net.ipv4.tcp_congestion_control = bbr
07-31 23:06:55.345 D/conversations(10988): ```',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('2b242914-9049-4e63-bcd1-0382e2d3d12b','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733593214,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'congestion_control invece funzia',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('04f4c522-6e59-44e4-afbf-7878c99a1dfa','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733698875,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'intanto va benissimo cosí, vedró piú avanti se questo crea problemi',5,8,0,NULL,NULL,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('4c2abd0a-9cd1-4060-93b6-4a1092cb3146','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733717788,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'https://discuss.linuxcontainers.org/t/start-up-service-not-working-inside-lxd/6038',5,0,0,NULL,1617733717575578,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'9e85127c-5a28-4b6c-b0ce-446071a0b727'),('e227dfbf-782f-4180-8deb-350125b7f4db','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733739817,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'Dimmi che modulo serve e te lo abilito',5,0,0,NULL,1617733739604255,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'24aebb7f-f9ce-427d-b130-186dfebea175'),('ae5e47fc-ae23-4d33-a0a9-487da12b9c93','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617733776432,'JID_ANOTHER_NAME_REDACTED@conversations.im',NULL,'Ok! Dopo guardo, ora cena.',5,8,0,NULL,1617733776479809,'05478876963367ab3e90c1513f0ac354c01fa0abe0f7b6123ba98edb18d94d642c',0,'[]',1,0,NULL,'[]',0,0,NULL,NULL),('9fb42f25-1bbd-4397-8d01-11fa8a1d9b18','2eaf2711-c29c-4e67-95f8-a2ecadd866f0',1617734326357,'JID_ANOTHER_NAME_REDACTED@conversations.im/Conversations.Q_rF',NULL,'How can I fix it?
07-31 23:06:55.345 D/conversations(10988): You can''t. If you''re bothered by the messages, just edit the /etc/sysctl.conf and remove all the settings that cannot be changed.',5,0,0,NULL,1617734326357478,'0597da89738ac458cc0559f5e0bea0155d8214db7be8cb7d6789e718d5c330d07c',0,'[]',1,0,NULL,'[]',1,0,NULL,'75062ff5-438e-41f4-9f39-97b51a5da140');
07-31 23:06:55.345 D/conversations(10988): 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
07-31 23:06:55.346 D/conversations(10988): 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
07-31 23:06:55.346 D/conversations(10988): 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
07-31 23:06:55.346 D/conversations(10988): 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
07-31 23:06:55.346 D/conversations(10988): 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
07-31 23:06:55.346 D/conversations(10988): 	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
07-31 23:06:55.346 D/conversations(10988): 	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1919)
07-31 23:06:55.346 D/conversations(10988): 	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1841)
07-31 23:06:55.346 D/conversations(10988): 	at eu.siacs.conversations.services.ImportBackupService.importBackup(ImportBackupService.java:257)
07-31 23:06:55.346 D/conversations(10988): 	at eu.siacs.conversations.services.ImportBackupService.lambda$onStartCommand$0(ImportBackupService.java:108)
07-31 23:06:55.346 D/conversations(10988): 	at eu.siacs.conversations.services.ImportBackupService.$r8$lambda$_Gblybgouv1Yt7P2F13nA3J9Xfw(Unknown Source:0)
07-31 23:06:55.346 D/conversations(10988): 	at eu.siacs.conversations.services.ImportBackupService$$ExternalSyntheticLambda0.run(Unknown Source:6)
07-31 23:06:55.346 D/conversations(10988): 	at eu.siacs.conversations.utils.SerialSingleThreadExecutor$Runner.run(SerialSingleThreadExecutor.java:58)
07-31 23:06:55.346 D/conversations(10988): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-31 23:06:55.346 D/conversations(10988): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-31 23:06:55.346 D/conversations(10988): 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by resoli** [comment]
It is very likely that the problem was caused by these five bytes of garbage after `sudo sysctl -p /etc/sysctl.d/30-peertube-tcp.conf`: `c0 80 c0 80 0a` , extractig hexdump from the raw logcat:

**Comment by resoli** [comment]
While a patch is in the work (  https://github.com/iNPUTmice/Conversations/commit/67f021426bc94699c3ce3b066a61c3a3babe40a1 ), I managed to repair my backups: https://codeberg.org/resoli/sql2ceb
