### ISSUE TITLE
Crash while showing Profile with mobile Data

### ISSUE THREAD

**Issue by ustar20** [iNPUTmice/Conversations#4305]
Hi!
The issue is only when i'm using mobile data. The error never occurs while Wifi is active.
Every time when i try to view the profile the application crashes an throws following errors:

_java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at ConnectivityManager_Proxy.getRestrictBackgroundStatus(Unknown Source:22)
	at eu.siacs.conversations.ui.XmppActivity.isAffectedByDataSaver(XmppActivity.java:450)
	at eu.siacs.conversations.ui.EditAccountActivity.updateAccountInformation(EditAccountActivity.java:1048)
	at eu.siacs.conversations.ui.EditAccountActivity.onBackendConnected(EditAccountActivity.java:814)
	at eu.siacs.conversations.ui.XmppActivity$1.onServiceConnected(XmppActivity.java:117)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)_  

The base is an ejabberd Server behind a vpn connection. The vpn is always on, both in wifi and with mobile data.

Is there a known workaround?
thanks in advance

**Comment by licaon-kter** [comment]
Which version of the app? Which device? Android version?

**Comment by ustar20** [comment]
Sorry i forgot to write this important details. 
I tried a lot of versions and also forks like blabber or monocle chat. 
Actual i compiled the version 2.10.5+free on my own. In general it works fine, but the error is the same.

The Device is a Samsung Galaxy S10 SM-G973F/DS ; Android 11  (December 21 Update).

**Comment by licaon-kter** [comment]
Is the app excluded from battery optimisations?

Can you test with Cheogram or monocles chat too? They're forks, but just to exclude some issue when building.

**Comment by ustar20** [comment]
Battery-optimisation is disabled for all chat apps. I've tried blabber in different versions and also Monocles chat un 2.10.2 and 2.10.5 --> same problem. I will try Cheogram today but i expect the same error.

**Comment by licaon-kter** [comment]
What type of vpn is this? Via an app or integrated eg. L2TP or? Without a VPN does in crash?

**Comment by iNPUTmice** [comment]
I think it's just the platform that crashes. Not a bug in either of those app. We can add a work around (catch the exception)

**Comment by ustar20** [comment]
I'm using IPSEC-VPN with Strongswan. 
A work around would be great :-)

**Comment by ustar20** [comment]
> I think it's just the platform that crashes. Not a bug in either of those app. We can add a work around (catch the exception)

Hi. I've tested a bit and there are some confusing circumstances for me. The problem without WiFi connection throws an error if i want to edit the profile. But the applications restarts itself also during normal situations. I can reproduce this situation when i post an url in the conversation. Mostly the app restarts itself when there is a link in the chat and i'm not WiFi connected. Can it be that this is the same problem. Unfortunately there is no error message.

thank you

**Comment by licaon-kter** [comment]
adb logcat?
