### ISSUE TITLE
Crashing after change package name 

### ISSUE THREAD

**Issue by DEAM0** [iNPUTmice/Conversations#4323]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 16373
    java.lang.RuntimeException: Unable to start activity ComponentInfo{}: java.lang.NullPointerException: Attempt to read from field 'android.view.View com.z3ro.z3rochat.databinding.ActivityConversationsBinding.toolbar' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'android.view.View com.z3ro.z3rochat.databinding.ActivityConversationsBinding.toolbar' on a null object reference
        at com.z3ro.z3rochat.ui.ConversationsActivity.onCreate(ConversationsActivity.java:367)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
I/m.z3ro.z3rocha: Background young concurrent copying GC freed 41659(2528KB) AllocSpace objects, 1(20KB) LOS objects, 66% free, 11MB/35MB, paused 11.595ms total 892.567ms
I/Process: Sending signal. PID: 16373 SIG: 9

**Comment by iNPUTmice** [comment]
There is no need to change the package namespace. You want to change the application id.

**Comment by DEAM0** [comment]
just change package id?

**Comment by licaon-kter** [comment]
Did you read the README first?

**Comment by DEAM0** [comment]
> 

yes, now working
