### ISSUE TITLE
App crashes when pressing input field on draft or after pre-filling username

### ISSUE THREAD

**Issue by bertvandepoel** [iNPUTmice/Conversations#4334]
This might be Android 12 or OxygenOS specific, but recently I noticed that when I open up Conversations and then tap a username, then the input field to type my message to this person in the group chat, the app just crashes. This same thing happens if a draft is present in the input field. I did find that a long press select all, then cut, prevents crashing with the draft. Once I've sent a few messages, I can tap a username and it won't always crash. I'm not sure if this is related to whether or not the keyboard has to pop up, or exactly what is causing this. 

Below is the trace that's automatically generated after the crash. When I tell the app to transfer it, it fails, but at least I could copy it. If you need me to supply any further information or test certain things, feel free to let me know.

```
Version: 2.10.2.1+fcr(420)
Last Update: 2022-04-05
SHA-1: 20:ab:18:ba:4d:49:1d:f1:b7:bf:50:51:be:1f:e2:6e:b7:56:27:73

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at android.content.ClipDescription.getMimeType(ClipDescription.java:313)
	at eu.siacs.conversations.ui.util.EditMessageActionModeCallback.onCreateActionMode(EditMessageActionModeCallback.java:61)
	at android.widget.Editor$TextActionModeCallback.onCreateActionMode(Editor.java:4277)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:2902)
	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1010)
	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:966)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1039)
	at android.view.View.startActionMode(View.java:7698)
	at android.widget.Editor.startInsertionActionMode(Editor.java:2403)
	at android.widget.EditorExtImpl.startInsertionActionMode(EditorExtImpl.java:77)
	at android.widget.Editor.onTouchUpEvent(Editor.java:2681)
	at android.widget.TextView.onTouchEvent(TextView.java:11338)
	at android.view.View.dispatchTouchEvent(View.java:14632)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1911)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4256)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
	at android.view.View.dispatchPointerEvent(View.java:14899)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6749)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6520)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5989)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6012)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6186)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6020)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6243)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5993)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6012)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6020)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5993)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9028)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8979)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8935)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9171)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:179)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8210)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

**Comment by bertvandepoel** [comment]
Thanks for the super quick fix. Now fingers crossed here for a release some time soon. Thanks again :D
