### ISSUE TITLE
Crash on mobile Data

### ISSUE THREAD

**Issue by ustar20** [iNPUTmice/Conversations#4368]
I think it's just the platform that crashes. Not a bug in either of those app. We can add a work around (catch the exception)

_Originally posted by @iNPUTmice in https://github.com/iNPUTmice/Conversations/issues/4305#issuecomment-1091106114_

Hi!
Unfortunately the error already exists. Is there an other line in the code which should be edited? The App throws following error:
Version: 2.10.9+free [1382](42031)
Last Update: 2022-08-24
SHA-1: 55:54:08:7c:72:c4:3a:82:e0:96:80:67:62:28:20:b1:98:d2:10:ad

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at ConnectivityManager_Proxy.getRestrictBackgroundStatus(Unknown Source:22)
	at eu.siacs.conversations.services.XmppConnectionService.isDataSaverDisabled(XmppConnectionService.java:933)
	at eu.siacs.conversations.parser.MessageParser.parseEvent(MessageParser.java:222)
	at eu.siacs.conversations.parser.MessageParser.onMessagePacketReceived(MessageParser.java:1006)
	at eu.siacs.conversations.xmpp.XmppConnection.processMessage(XmppConnection.java:786)
	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:646)
	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:486)
	at eu.siacs.conversations.xmpp.XmppConnection.switchOverToTls(XmppConnection.java:816)
	at eu.siacs.conversations.xmpp.XmppConnection.processStream(XmppConnection.java:470)
	at eu.siacs.conversations.xmpp.XmppConnection.connect(XmppConnection.java:382)
	at eu.siacs.conversations.xmpp.XmppConnection.run(XmppConnection.java:457)
	at java.lang.Thread.run(Thread.java:923)

**Comment by ustar20** [comment]
Thank you very much for your support. It looks like it works :-)
