### ISSUE TITLE
Crash on device without camera

### ISSUE THREAD

**Issue by 66tree** [iNPUTmice/Conversations#4370]
I installed Conversations on [AYN Odin Pro](https://www.ayntec.com/collections/odin). I tested audio calls and that worked but when I tried video it crashed Conversations with this error:
    Version: 2.10.10+playstore(42038)
    Last Update: 2022-09-01
    SHA-1: 6f:80:8b:e7:c4:81:e6:f0:16:f7:19:ba:9d:6e:d7:af:c3:1c:44:5e
    
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	    at eu.siacs.conversations.ui.service.CameraManager.getTorchEnabled(CameraManager.java:284)
	    at eu.siacs.conversations.ui.service.CameraManager.setTorch(CameraManager.java:279)
	    at eu.siacs.conversations.ui.ScanActivity.lambda$onKeyDown$0(ScanActivity.java:254)
	    at eu.siacs.conversations.ui.ScanActivity.$r8$lambda$T5YV6IVFFYqu5qfiXFEPayx5dT8(Unknown Source:0)
	    at eu.siacs.conversations.ui.ScanActivity$$ExternalSyntheticLambda1.run(Unknown Source:4)
	    at android.os.Handler.handleCallback(Handler.java:883)
	    at android.os.Handler.dispatchMessage(Handler.java:100)
	    at android.os.Looper.loop(Looper.java:214)
	    at android.os.HandlerThread.run(HandlerThread.java:67)

Seems like the video option shouldn't be there on this device.

**Comment by iNPUTmice** [comment]
The crash you posted is from the QR code scanner? How did you get into the QR code scanner? All entry points to the scanner should be disabled.

**Comment by iNPUTmice** [comment]
No reaction from op. closing here.
